-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE recipes (
--     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     receipe_name TEXT,
--     recipe_data JSONB
-- );
DROP TABLE IF EXISTS recipes;