CREATE TABLE dishes (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_name        TEXT,
    dish_data        JSONB,
    parent_dish_id   INT REFERENCES dishes(id),
    parent_recipe_id INT REFERENCES recipes(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
