CREATE TABLE short_urls (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code  TEXT NOT NULL UNIQUE,
    target_type TEXT NOT NULL,
    target_id   TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
