-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- Create DOMAIN for chef_type if it doesn't exist
-- CREATE DOMAIN chef_type_enum AS TEXT
--   CHECK (VALUE IN ('beginner', 'homecook', 'professional'));
--
-- -- Create review_instance table
-- CREATE TABLE review_instance (
--   id            CHAR(6) NOT NULL,
--   dish_id       INT NOT NULL REFERENCES dishes(id) ON DELETE CASCADE,
--   name          TEXT NOT NULL,
--   timestamp     TIMESTAMPTZ NOT NULL DEFAULT now(),
--   chef_type     chef_type_enum NOT NULL,
--   event_context TEXT,
--   notes         TEXT,
--   difficulty    INT CHECK (difficulty >= 1 AND difficulty <= 5),
--
--   PRIMARY KEY (dish_id, id)
-- );
--
-- -- Create indexes for common queries
-- CREATE INDEX idx_review_instance_dish_id ON review_instance(dish_id);
-- CREATE INDEX idx_review_instance_timestamp ON review_instance(timestamp DESC);
-- CREATE INDEX idx_review_instance_chef_type ON review_instance(chef_type);
