// Recipe data — meat-dish-forward titles with cruelty-free phrasing in each language.
// Title format: "[Familiar dish name] ([cruelty-free phrase])"

const CUISINES = [
  { id: "all",            name: "All",             tag: "Cruelty-free, restaurant-grade" },
  { id: "italian",        name: "Italian",         tag: "Senza crudeltà" },
  { id: "french",         name: "French",          tag: "Sans cruauté" },
  { id: "german",         name: "German",          tag: "Tierleidfrei" },
  { id: "indian",         name: "Indian",          tag: "क्रूरता मुक्त · Kroorta mukt" },
  { id: "mexican",        name: "Mexican",         tag: "Sin crueldad" },
  { id: "japanese",       name: "Japanese",        tag: "虐待なし · Gyakutai nashi" },
  { id: "thai",           name: "Thai",            tag: "ปราศจากการทารุณกรรม · Pratsachak kan tharunakam" },
  { id: "chinese",        name: "Chinese",         tag: "无虐待 · Wú nüèdài" },
  { id: "middle-eastern", name: "Middle Eastern",  tag: "بدون قسوة · Bidun qaswa" },
  { id: "mediterranean",  name: "Mediterranean",   tag: "Χωρίς σκληρότητα · Chorís sklirótita" },
  { id: "american",       name: "American",        tag: "No Cruelty"},
  { id: "korean",         name: "Korean",          tag: "동물 학대 없음 · Dongmul hakdae eops-eum" },
  { id: "vietnamese",     name: "Vietnamese",      tag: "Không ngược đãi" },
  { id: "caribbean",      name: "Caribbean",       tag: "No Cruelty"},
  { id: "ethiopian",      name: "Ethiopian",       tag: "ያለ ግፍ · Yale gif" },
  { id: "spanish",        name: "Spanish",         tag: "Sin crueldad" },
];

function PhotoPH({ palette, label, dish }) {
  const bg = palette[0];
  const a = palette[1];
  const b = palette[2];
  let layers = "";
  if (dish === "bowl") {
    layers = `
      radial-gradient(ellipse 55% 38% at 50% 60%, ${a} 0%, ${a} 35%, transparent 60%),
      radial-gradient(ellipse 30% 18% at 50% 56%, ${b} 0%, transparent 70%),
      radial-gradient(circle at 30% 35%, oklch(0.96 0.02 85 / 0.18) 0%, transparent 30%)
    `;
  } else if (dish === "plate") {
    layers = `
      radial-gradient(circle at 50% 55%, ${a} 0%, ${a} 32%, transparent 34%),
      radial-gradient(circle at 50% 55%, ${b} 0%, ${b} 18%, transparent 20%),
      radial-gradient(circle at 35% 45%, oklch(0.96 0.02 85 / 0.2) 0%, transparent 18%)
    `;
  } else if (dish === "flat") {
    layers = `
      linear-gradient(135deg, ${a} 0%, ${a} 50%, ${b} 50%, ${b} 100%),
      radial-gradient(circle at 30% 30%, oklch(0.96 0.02 85 / 0.2) 0%, transparent 25%)
    `;
  } else {
    layers = `
      linear-gradient(180deg, transparent 0%, transparent 55%, ${a} 55%, ${a} 75%, ${b} 75%, ${b} 100%),
      radial-gradient(ellipse 40% 20% at 50% 55%, ${a} 0%, transparent 70%)
    `;
  }
  return (
    <div className="photo-ph" style={{
      background: `${layers}, ${bg}`,
    }}>
      <div className="label">{label || "food photo"}</div>
    </div>
  );
}

const PALETTES = {
  italian: ['oklch(0.72 0.12 35)', 'oklch(0.55 0.16 28)', 'oklch(0.85 0.08 90)'],
  french: ['oklch(0.78 0.06 80)', 'oklch(0.65 0.10 70)', 'oklch(0.42 0.08 50)'],
  german: ['oklch(0.50 0.10 50)', 'oklch(0.65 0.10 70)', 'oklch(0.42 0.08 40)'],
  indian: ['oklch(0.62 0.16 60)', 'oklch(0.55 0.18 35)', 'oklch(0.75 0.14 85)'],
  mexican: ['oklch(0.58 0.16 30)', 'oklch(0.70 0.16 70)', 'oklch(0.55 0.15 140)'],
  japanese: ['oklch(0.78 0.04 130)', 'oklch(0.45 0.10 30)', 'oklch(0.92 0.02 100)'],
  thai: ['oklch(0.70 0.15 75)', 'oklch(0.55 0.16 140)', 'oklch(0.62 0.18 30)'],
  chinese: ['oklch(0.55 0.16 30)', 'oklch(0.42 0.10 50)', 'oklch(0.78 0.12 75)'],
  'middle-eastern': ['oklch(0.62 0.10 60)', 'oklch(0.50 0.12 40)', 'oklch(0.75 0.10 90)'],
  mediterranean: ['oklch(0.68 0.14 140)', 'oklch(0.78 0.10 90)', 'oklch(0.55 0.14 35)'],
  american: ['oklch(0.55 0.14 35)', 'oklch(0.72 0.13 75)', 'oklch(0.42 0.08 50)'],
  korean: ['oklch(0.55 0.18 30)', 'oklch(0.62 0.16 140)', 'oklch(0.85 0.06 90)'],
  vietnamese: ['oklch(0.72 0.14 130)', 'oklch(0.78 0.10 80)', 'oklch(0.55 0.14 35)'],
  caribbean: ['oklch(0.68 0.16 70)', 'oklch(0.55 0.16 140)', 'oklch(0.58 0.16 30)'],
  ethiopian: ['oklch(0.55 0.14 50)', 'oklch(0.45 0.10 30)', 'oklch(0.78 0.10 90)'],
  spanish: ['oklch(0.62 0.16 50)', 'oklch(0.78 0.13 75)', 'oklch(0.45 0.12 30)'],
};

function paletteFor(c) { return PALETTES[c] || PALETTES.italian; }

const RECIPES = [
  {
    id: 'r01',
    title: 'Bistecca alla Fiorentina (Senza crudeltà)',
    source: 'Watermelon · seared & smoked',
    cuisine: 'italian', cuisineName: 'Italian',
    photo: 'plate', photoLabel: 'steak · char · rosemary',
    why: 'Compressed watermelon takes a hard cast-iron sear; reads as rare T-bone, plates whole at the table.',
    prep: '40m', serves: 2, difficulty: 3, cost: 4.20,
    ingredients: [
      'Watermelon — 1 large seedless, cut into 2 thick T-bone-shaped slabs (about 1.5 in thick)',
      'Extra-virgin olive oil — 3 tbsp, for searing and finishing',
      'Fleur de sel — 1 tsp, for crust',
      'Coarse black pepper — 1 tsp, freshly cracked',
      'Fresh rosemary — 2 sprigs, bruised',
      'Fresh thyme — 4 sprigs',
      'Garlic — 2 cloves, crushed in skin',
      'Liquid smoke — 1 tsp (or hickory chips for actual smoker)',
      'Balsamic reduction — 2 tbsp, aged, for finishing drizzle',
      'Lemon — 1, halved, for service',
      'White truffle oil — 1 tsp, optional finish',
      'Arugula — 2 large handfuls, dressed simply with lemon and olive oil',
    ],
    equipment: ['Cast iron', 'Vacuum sealer', 'Smoker'],
    subs: [
      ['Watermelon', 'King trumpet (year-round)'],
      ['Watermelon', 'Celeriac slab (gluten-free, nut-free)'],
      ['Truffle oil', 'Herb oil (budget)'],
    ],
    steps: [
      'Vacuum-seal watermelon slabs with 1 tsp salt and olive oil; compress 20 min or overnight.',
      'Pat slabs dry; season aggressively with fleur de sel and cracked black pepper on all faces.',
      'Heat cast iron until screaming hot (5 min); add 1 tbsp olive oil and sear slabs 3 min undisturbed.',
      'Flip once; add rosemary, thyme, and crushed garlic to the pan; baste continuously 2 min.',
      'Transfer to smoker at 200°F with liquid smoke or hickory chips; smoke 10 min.',
      'Rest 5 min on a wire rack; slice thin across the grain parallel to the rind edge.',
      'Finish with fleur de sel, balsamic reduction, and optional truffle oil at the pass.',
      'Plate on a warmed board with dressed arugula and lemon halves; serve whole tableside.',
    ],
    badge: 'Showpiece',
  },
  {
    id: 'r02',
    title: 'Ossobuco (Senza crudeltà)',
    source: 'Celeriac · slow-braised',
    cuisine: 'italian', cuisineName: 'Italian',
    photo: 'bowl', photoLabel: 'braise · gremolata · marrow',
    why: 'Whole celeriac braises 3 hours in red wine; "marrow" is cashew-miso butter spooned at the pass.',
    prep: '3h', serves: 4, difficulty: 2, cost: 4.80,
    ingredients: [
      'Celeriac — 2 large bulbs, each cut into 2 rounds (3 in thick), strings trimmed',
      'Dry red wine — 1 cup (Barolo or Chianti preferred)',
      'Crushed tomato — 1 can (400g), San Marzano',
      'Vegetable stock — 2 cups, rich',
      'Yellow onion — 1 large, finely diced',
      'Carrot — 2 medium, finely diced',
      'Celery — 2 stalks, finely diced',
      'Garlic — 4 cloves, minced',
      'Tomato paste — 2 tbsp',
      'Olive oil — 3 tbsp',
      'Cashew-miso butter — 4 tbsp (1 cup raw cashews blended with 2 tbsp white miso, 2 tbsp water)',
      'Gremolata — 1 small bunch flat-leaf parsley (minced), zest of 1 lemon, 2 garlic cloves (minced)',
      'Bay leaf — 2',
      'Fresh thyme — 4 sprigs',
      'Fleur de sel and black pepper — to taste',
    ],
    equipment: ['Dutch oven', 'Blender'],
    subs: [
      ['Celeriac', 'King trumpet (year-round option)'],
      ['Cashew-miso butter', 'Sunflower-seed butter + miso (nut-free)'],
      ['Red wine', 'Pomegranate juice + balsamic (alcohol-free)'],
    ],
    steps: [
      'Season celeriac rounds with salt and pepper; sear in olive oil in Dutch oven 4 min per side until golden.',
      'Remove celeriac; sweat onion, carrot, celery in same pot 10 min until soft.',
      'Add garlic and tomato paste; cook out 2 min until paste darkens slightly.',
      'Deglaze with red wine; reduce by half, scraping up fond, about 4 min.',
      'Add crushed tomato, stock, bay, and thyme; nestle celeriac rounds back in.',
      'Cover and braise at 325°F (or low simmer) for 2.5–3 h until celeriac is fork-tender throughout.',
      'Remove celeriac; reduce braising liquid 5 min to sauce consistency; adjust seasoning.',
      'Spoon cashew-miso butter into the bone cavity of each round at the pass.',
      'Ladle sauce over; finish with gremolata; serve with saffron risotto or polenta.',
    ],
    badge: 'Sunday service',
  },
  {
    id: 'r03',
    title: 'Steak Frites (Sans cruauté)',
    source: 'King trumpet · seared',
    cuisine: 'french', cuisineName: 'French',
    photo: 'flat', photoLabel: 'steak · frites · béarnaise',
    why: 'Score and press king trumpets into hanger-steak shape; double-fry frites; aquafaba béarnaise holds 2h.',
    prep: '35m', serves: 2, difficulty: 2, cost: 5.10,
    ingredients: [
      'King trumpet mushrooms — 6 large, halved lengthwise and scored crosshatch',
      'Idaho potato — 3 large, cut into 1/4-in batons, soaked in cold water',
      'Aquafaba — 6 tbsp (from unsalted chickpea can)',
      'Fresh tarragon — 1 small bunch, leaves picked',
      'Shallot — 2, finely minced',
      'White wine vinegar — 2 tbsp',
      'Dry white wine — 2 tbsp',
      'Vegan butter — 4 tbsp (melted and warm, for béarnaise emulsion)',
      'Dijon mustard — 1 tsp',
      'Neutral oil — for frying',
      'Fleur de sel — to taste',
      'Cracked black pepper — to taste',
      'Fresh flat-leaf parsley — 1 tbsp, chopped, for garnish',
    ],
    equipment: ['Cast iron', 'Fryer', 'Blender'],
    subs: [
      ['King trumpet', 'Lion\'s mane (similar texture)'],
      ['King trumpet', 'Thick-sliced portobello (budget)'],
      ['Aquafaba béarnaise', 'Cashew-tarragon sauce (no aquafaba; nut risk)'],
    ],
    steps: [
      'Reduce shallot with white wine and vinegar to 2 tbsp in small saucepan; cool slightly.',
      'Blend aquafaba 30 sec until foamy; stream in warm vegan butter slowly until emulsified.',
      'Fold in reduction, tarragon, Dijon, salt; hold béarnaise at 120°F in a bain-marie.',
      'First-fry potatoes at 300°F for 5 min until just cooked through; drain on rack.',
      'Press scored king trumpet halves flat with a weight; season aggressively with salt and pepper.',
      'Sear mushrooms in cast iron with butter-side down 3 min, flip, 2 min; baste with pan juices.',
      'Second-fry potatoes at 375°F until golden and crisp, about 3 min; season immediately with fleur de sel.',
      'Plate steak alongside frites; spoon béarnaise tableside or pass separately in a ramekin.',
    ],
    badge: 'Bistro classic',
  },
  {
    id: 'r04',
    title: 'Bœuf Bourguignon (Sans cruauté)',
    source: 'Cremini & seitan · braised',
    cuisine: 'french', cuisineName: 'French',
    photo: 'bowl', photoLabel: 'stew · red wine · pearl onion',
    why: 'Deep red-wine braise with seared seitan; tastes like 4-hour beef stew, ready in 50 minutes.',
    prep: '50m', serves: 6, difficulty: 2, cost: 4.20,
    ingredients: [
      'Seitan — 600g, cut into 1.5-in chunks',
      'Cremini mushrooms — 400g, quartered',
      'Burgundy (or other dry red wine) — 2 cups',
      'Pearl onions — 200g, blanched and peeled',
      'Tomato paste — 3 tbsp',
      'Vegetable stock — 1.5 cups',
      'Carrot — 2 large, cut into 1-in pieces',
      'Celery — 2 stalks, cut into 1-in pieces',
      'Garlic — 4 cloves, smashed',
      'Vegan butter — 2 tbsp, for finishing',
      'Fresh thyme — 5 sprigs',
      'Bay leaf — 2',
      'All-purpose flour — 2 tbsp, for dredging seitan',
      'Olive oil — 3 tbsp',
      'Flat-leaf parsley — 2 tbsp, chopped, for finish',
    ],
    equipment: ['Dutch oven'],
    subs: [
      ['Seitan', 'King trumpet (gluten-free)'],
      ['Seitan', 'Lentil-walnut balls (gluten-free, nut allergen note)'],
      ['Pearl onions', 'Cipollini onions (same treatment)'],
    ],
    steps: [
      'Dredge seitan chunks lightly in flour; sear in olive oil in Dutch oven until browned on all sides, 6 min.',
      'Remove seitan; sauté cremini in same pot until golden and liquid evaporates, 5 min.',
      'Add garlic, tomato paste; cook 2 min until paste deepens in color.',
      'Deglaze with Burgundy; reduce by one-third, about 4 min.',
      'Add stock, thyme, bay, carrot, celery, and pearl onions; return seitan.',
      'Simmer covered 30 min until vegetables are tender and seitan has absorbed the braise.',
      'Remove lid; reduce sauce 5 min to coat the back of a spoon; swirl in vegan butter.',
      'Taste and adjust salt; finish with parsley; hold at 160°F in the bain for service.',
    ],
    badge: 'Crowd favorite',
  },
  {
    id: 'r05',
    title: 'Sauerbraten (Tierleidfrei)',
    source: 'Seitan · 3-day marinated',
    cuisine: 'german', cuisineName: 'German',
    photo: 'plate', photoLabel: 'braise · gingersnap · red cabbage',
    why: 'Three-day red-wine-vinegar marinade penetrates seitan like a real Sauerbraten roast; gingersnap gravy thickens at service.',
    prep: '3d marinade · 60m cook', serves: 6, difficulty: 3, cost: 4.10,
    ingredients: [
      'Seitan — 800g, formed into a single roast block',
      'Red wine vinegar — 1 cup',
      'Dry red wine — 1 cup',
      'Water — 1 cup',
      'Yellow onion — 2, sliced',
      'Carrot — 2, sliced',
      'Whole cloves — 6',
      'Juniper berries — 8, lightly crushed',
      'Bay leaf — 3',
      'Gingersnap cookies (vegan) — 6, crumbled, for gravy',
      'Brown sugar — 2 tbsp',
      'Raisins — 3 tbsp',
      'Vegetable oil — 2 tbsp, for browning',
      'Salt and black pepper — to taste',
      'Red cabbage — 1/2 head, braised separately with apple and vinegar for service',
    ],
    equipment: ['Dutch oven', 'Vacuum bag'],
    subs: [
      ['Seitan', 'King trumpet (gluten-free)'],
      ['Gingersnap cookies', 'Gluten-free ginger snaps (gluten-free)'],
      ['Red wine', 'Red grape juice + 1 tbsp balsamic (alcohol-free)'],
    ],
    steps: [
      'Combine vinegar, wine, water, onion, carrot, cloves, juniper, bay, sugar, and raisins; bring to a simmer 5 min, cool.',
      'Submerge seitan roast in marinade; vacuum-seal or place in a deep container covered; refrigerate 3 days, turning daily.',
      'Remove seitan from marinade; pat dry; strain and reserve marinade.',
      'Brown seitan roast in oil in Dutch oven on all sides, about 8 min.',
      'Pour reserved marinade over; braise covered at 325°F for 45 min, turning once.',
      'Remove seitan; strain braising liquid into a saucepan; whisk in crumbled gingersnaps over medium heat.',
      'Simmer gravy 5 min until thickened to sauce consistency; adjust sweet-sour balance.',
      'Slice seitan across the grain; plate with braised red cabbage and potato dumplings; ladle gravy over.',
    ],
    badge: 'Sunday service',
  },
  {
    id: 'r06',
    title: 'Currywurst (Tierleidfrei)',
    source: 'House-made seitan sausage',
    cuisine: 'german', cuisineName: 'German',
    photo: 'flat', photoLabel: 'sausage · curry · ketchup',
    why: 'Seitan sausage poaches in batches; curry-ketchup is your one sauce. Imbiss-ready in 90 seconds.',
    prep: '40m', serves: 6, difficulty: 1, cost: 2.40,
    ingredients: [
      'Vital wheat gluten — 300g',
      'Chickpea flour — 50g',
      'Nutritional yeast — 3 tbsp',
      'Marjoram — 1 tsp, dried',
      'Smoked paprika — 2 tsp',
      'Garlic powder — 1 tsp',
      'Onion powder — 1 tsp',
      'Soy sauce — 2 tbsp',
      'Vegetable stock — 250ml, for mixing dough',
      'Tomato passata — 1 cup, for curry-ketchup sauce',
      'Curry powder — 2 tbsp (hot or mild), for sauce',
      'Apple cider vinegar — 1 tbsp, for sauce balance',
      'Brown sugar — 1 tsp, for sauce',
      'Neutral oil — 1 tbsp, for finishing sear',
    ],
    equipment: ['Steamer', 'Cast iron'],
    subs: [
      ['Wheat gluten', 'Tofu base (gluten-free)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
    ],
    steps: [
      'Mix vital wheat gluten, chickpea flour, nutritional yeast, spices, and soy sauce with stock into a stiff dough.',
      'Divide into 6 equal logs; wrap each tightly in oiled foil, twisting ends like a cracker.',
      'Steam wrapped sausages 25 min; cool slightly, then remove foil.',
      'Simmer tomato passata with curry powder, vinegar, and sugar 10 min; blend smooth; hold hot.',
      'Sear sausages on cast iron 2 min per side until skin is lightly crisped.',
      'Slice into 1-in rounds on the plate; spoon curry-ketchup generously over.',
      'Dust with extra curry powder at the pass; serve with a small fork.',
    ],
    badge: 'Quick-fire',
  },
  {
    id: 'r07',
    title: 'Butter Chicken (Kroorta mukt)',
    source: 'Cauliflower · charred',
    cuisine: 'indian', cuisineName: 'Indian',
    photo: 'bowl', photoLabel: 'tomato · cream · charred florets',
    why: 'Tandoor-charred cauliflower in a cashew-tomato gravy; the table can\'t tell. Sauce holds 3 days.',
    prep: '40m', serves: 6, difficulty: 2, cost: 3.10,
    ingredients: [
      'Cauliflower — 1 large head, cut into large florets',
      'Cashews — 1 cup, soaked 4h in hot water, drained',
      'Crushed tomato — 1 can (400g)',
      'Fenugreek leaves (kasuri methi) — 1 tbsp, dried',
      'Garam masala — 2 tsp',
      'Ground cumin — 1 tsp',
      'Ground coriander — 1 tsp',
      'Kashmiri chili powder — 1 tsp (for color and mild heat)',
      'Fresh ginger — 1.5-in piece, grated',
      'Garlic — 4 cloves, minced',
      'Yellow onion — 1 large, roughly chopped',
      'Coconut cream — 3 tbsp, for sauce richness',
      'Neutral oil — 3 tbsp',
      'Salt — to taste',
      'Fresh cilantro — 2 tbsp, for garnish',
    ],
    equipment: ['Tandoor or grill', 'Blender', 'Heavy pot'],
    subs: [
      ['Cauliflower', 'Soy curls (rehydrated)'],
      ['Cashews', 'Blanched almonds (same method)'],
      ['Cashews', 'Sunflower-seed cream (nut-free)'],
      ['Coconut cream', 'Oat cream (coconut-free)'],
    ],
    steps: [
      'Toss cauliflower florets in oil, salt, and half the spices; char in tandoor or under a 500°F broiler 10 min.',
      'Sauté onion in oil over medium-high heat 8 min until golden; add garlic and ginger, cook 2 min.',
      'Add tomato paste and crushed tomato; simmer 10 min until oil separates at the edges.',
      'Transfer tomato-onion base to blender with soaked cashews; blitz until completely smooth.',
      'Return sauce to pot; add remaining spices, kasuri methi, and coconut cream; simmer 8 min.',
      'Fold charred cauliflower into sauce; simmer 5 min to marry flavors.',
      'Adjust salt; finish with a pinch of garam masala and cilantro at the pass.',
      'Hold at 160°F in a bain-marie; serve with basmati rice and warm naan.',
    ],
    badge: 'Crowd favorite',
  },
  {
    id: 'r08',
    title: 'Lamb Rogan Josh (Kroorta mukt)',
    source: 'Jackfruit & black lentil',
    cuisine: 'indian', cuisineName: 'Indian',
    photo: 'bowl', photoLabel: 'kashmiri · chile · yogurt',
    why: 'Slow-cooked jackfruit pulls like lamb shoulder; black lentils provide the fat and structure.',
    prep: '90m', serves: 8, difficulty: 2, cost: 2.40,
    ingredients: [
      'Young jackfruit (canned, in brine) — 2 cans (560g each), drained, rinsed, shredded',
      'Whole urad (black lentils) — 1 cup, soaked overnight',
      'Kashmiri chili — 4 whole dried, soaked then ground to paste',
      'Whole green cardamom — 6 pods',
      'Whole black cardamom — 2 pods',
      'Cinnamon stick — 2-in piece',
      'Cloves — 4 whole',
      'Yellow onion — 2 large, thinly sliced',
      'Fresh ginger — 2-in piece, grated',
      'Garlic — 5 cloves, minced',
      'Coconut yogurt — 6 tbsp, for finishing',
      'Fennel powder — 1 tsp',
      'Ginger powder — 1 tsp',
      'Mustard oil — 3 tbsp (or neutral oil)',
      'Salt — to taste',
    ],
    equipment: ['Pressure cooker', 'Heavy pot'],
    subs: [
      ['Jackfruit', 'Soy curls (rehydrated)'],
      ['Coconut yogurt', 'Cashew yogurt (coconut-free)'],
      ['Coconut yogurt', 'Oat yogurt (coconut-free, nut-free)'],
    ],
    steps: [
      'Pressure-cook soaked urad lentils with 2 cups water 25 min until soft; set aside.',
      'Bloom whole spices (cardamom, cinnamon, cloves) in hot mustard oil in heavy pot 1 min.',
      'Sauté sliced onion 15 min until deep golden; add ginger and garlic, cook 2 min.',
      'Stir in Kashmiri chili paste, fennel powder, ginger powder; cook 3 min until oil separates.',
      'Add shredded jackfruit; fold to coat in masala; cook on high heat 5 min to develop color.',
      'Add cooked lentils and 1 cup water; simmer covered 40 min, stirring occasionally.',
      'Uncover; reduce until gravy coats jackfruit deeply; adjust salt.',
      'Swirl in coconut yogurt off heat; garnish with julienned ginger; serve with rice or roti.',
    ],
    badge: 'Service-friendly',
  },
  {
    id: 'r09',
    title: 'Carnitas Tacos (Sin crueldad)',
    source: 'Jackfruit & oyster mushroom',
    cuisine: 'mexican', cuisineName: 'Mexican',
    photo: 'flat', photoLabel: 'pulled · char · lime',
    why: 'Jackfruit-mushroom blend confit\'d in olive oil; crisped on the flat-top to order. Two-minute build.',
    prep: '60m', serves: 8, difficulty: 2, cost: 2.80,
    ingredients: [
      'Young jackfruit (canned, in brine) — 2 cans (560g each), drained and shredded',
      'Oyster mushrooms — 300g, torn into strips',
      'Orange — 1, juiced and zested',
      'Bay leaf — 3',
      'Cumin seeds — 1 tsp',
      'Dried oregano — 1 tsp',
      'Chipotle in adobo — 1 pepper + 1 tbsp sauce',
      'Garlic — 4 cloves, smashed',
      'Olive oil — 1/2 cup, for confit',
      'Corn tortillas — 16 (2 per person), charred on flame',
      'White onion — 1/2, finely diced, for serving',
      'Fresh cilantro — 1 bunch, for serving',
      'Lime — 2, cut into wedges',
      'Salsa verde or salsa roja — 1 cup, for service',
    ],
    equipment: ['Heavy pot', 'Flat-top'],
    subs: [
      ['Oyster mushroom', 'King oyster (meatier texture)'],
      ['Corn tortillas', 'Flour tortillas (if gluten acceptable)'],
    ],
    steps: [
      'Combine jackfruit, mushrooms, orange juice and zest, bay, cumin, oregano, chipotle, and garlic in heavy pot.',
      'Cover with olive oil; confit on low heat 45 min until jackfruit is very tender and pulls easily.',
      'Drain, reserving the confit oil; shred jackfruit with two forks and fold mushrooms through.',
      'Char tortillas directly on open flame or dry griddle 30 sec per side; keep warm in foil.',
      'At service: ladle a portion of carnitas on flat-top; press flat; sear 90 sec until crispy edges form.',
      'Double-stack tortillas; fill with crisped carnitas; add diced onion and cilantro.',
      'Squeeze lime over at the pass; serve immediately with salsa on the side.',
    ],
    badge: 'Quick-fire',
  },
  {
    id: 'r10',
    title: 'Beef Birria (Sin crueldad)',
    source: 'Soy curls & beet',
    cuisine: 'mexican', cuisineName: 'Mexican',
    photo: 'bowl', photoLabel: 'birria · guajillo · consomé',
    why: 'Five-chile broth with beet-blooded soy curls; consomé is the showstopper, holds in a bain-marie.',
    prep: '75m', serves: 6, difficulty: 3, cost: 3.40,
    ingredients: [
      'Soy curls — 200g dry, rehydrated in warm water 10 min',
      'Guajillo chiles — 5, stemmed, seeded, toasted',
      'Ancho chiles — 3, stemmed, seeded, toasted',
      'Pasilla chiles — 2, stemmed, seeded, toasted',
      'Raw beet — 1 large, roasted and blended for color',
      'Mexican oregano — 2 tsp',
      'Cumin — 1 tsp, ground',
      'Cinnamon — 1/2 stick',
      'Whole cloves — 4',
      'Garlic — 5 cloves',
      'White onion — 1 large, quartered and charred',
      'Corn tortillas — 12, for quesabirria service',
      'Vegan cheese — 100g, shredded, for quesabirria (optional)',
      'Vegetable stock — 6 cups',
      'Apple cider vinegar — 1 tbsp',
    ],
    equipment: ['Stock pot', 'High-speed blender'],
    subs: [
      ['Soy curls', 'Jackfruit (soy-free)'],
      ['Soy curls', 'King trumpet (soy-free, meaty)'],
      ['Corn tortillas', 'Cassava tortillas (grain-free option)'],
    ],
    steps: [
      'Toast dried chiles in dry skillet 30 sec per side; soak in hot water 20 min until pliable.',
      'Char onion and garlic directly on an open flame or dry comal until blackened in spots.',
      'Blend soaked chiles with charred onion, garlic, beet, oregano, cumin, cinnamon, and cloves; add 1 cup stock.',
      'Strain chile paste through a mesh strainer into stock pot; simmer paste 5 min.',
      'Add remaining stock and vinegar; bring to a boil; reduce to a simmer.',
      'Add rehydrated soy curls; simmer 30 min until curls are deeply colored and tender.',
      'Adjust salt; hold consomé in a bain-marie at 160°F for service.',
      'For quesabirria: dip tortillas in consomé surface fat, griddle with filling, fold and crisp.',
      'Serve birria in a bowl with consomé alongside for dipping.',
    ],
    badge: 'Showpiece',
  },
  {
    id: 'r11',
    title: 'Wagyu Donburi (Gyakutai nashi)',
    source: 'King trumpet · seared',
    cuisine: 'japanese', cuisineName: 'Japanese',
    photo: 'bowl', photoLabel: 'rice · sear · scallion',
    why: 'King trumpets sliced thin, seared rare in a soy-mirin glaze; reads as wagyu over koshihikari.',
    prep: '20m', serves: 4, difficulty: 1, cost: 3.60,
    ingredients: [
      'King trumpet mushrooms — 6 large, sliced lengthwise 1/4-in thick',
      'Koshihikari short-grain rice — 2 cups, cooked per package (or rice cooker)',
      'Soy sauce — 3 tbsp (tamari for GF)',
      'Mirin — 3 tbsp',
      'Sake — 2 tbsp',
      'Brown sugar — 1 tsp',
      'Toasted sesame oil — 1 tsp, for finishing',
      'Neutral oil — 1 tbsp, for searing',
      'Scallion — 4, thinly sliced on a bias',
      'Toasted sesame seeds — 1 tsp',
      'Shichimi togarashi — pinch, for heat',
      'Pickled ginger (gari) — 2 tbsp, for service',
    ],
    equipment: ['Carbon-steel pan', 'Rice cooker'],
    subs: [
      ['King trumpet', 'Hen-of-the-woods (maitake)'],
      ['Soy sauce', 'Tamari (gluten-free)'],
      ['Soy sauce + mirin', 'Coconut aminos + mirin (soy-free, slightly sweeter)'],
    ],
    steps: [
      'Combine soy sauce, mirin, sake, and brown sugar in a small bowl; stir to dissolve.',
      'Heat carbon-steel pan until smoking; add neutral oil.',
      'Sear king trumpet slices in a single layer 90 sec per side until mahogany and caramelized.',
      'Add glaze to pan; toss mushrooms rapidly 30 sec until lacquered; remove from heat.',
      'Portion hot rice into bowls; fan mushroom slices over the top decoratively.',
      'Drizzle sesame oil; scatter scallion and sesame seeds; add a pinch of shichimi.',
      'Finish with 2 tsp of pickled ginger per bowl; serve immediately.',
    ],
    badge: 'Weeknight hero',
  },
  {
    id: 'r12',
    title: 'Tonkotsu Ramen (Gyakutai nashi)',
    source: 'Soy milk & shiitake dashi',
    cuisine: 'japanese', cuisineName: 'Japanese',
    photo: 'bowl', photoLabel: 'ramen · cloud · tare',
    why: 'Soy-milk emulsion mimics tonkotsu\'s collagen body; shiitake-kombu dashi does the porcine work.',
    prep: '60m', serves: 6, difficulty: 2, cost: 3.95,
    ingredients: [
      'Unsweetened soy milk — 3 cups',
      'Dried shiitake mushrooms — 30g, cold-soaked overnight',
      'Kombu — 10g (2 large pieces)',
      'Ramen noodles — 600g fresh (or 300g dried)',
      'Marinated tofu — 400g, sliced (tofu pressed, marinated in soy, mirin, ginger, then broiled)',
      'Shiro miso — 3 tbsp, for tare',
      'Soy sauce — 2 tbsp, for tare',
      'Toasted sesame paste — 2 tbsp',
      'Dried shiitake soaking water — 2 cups, strained (reserve from above)',
      'Scallion — 4, thinly sliced',
      'Nori — 2 sheets, cut into rectangles',
      'Soft-boiled aquafaba "egg" or tofu egg — optional garnish',
      'Mayu (black garlic oil) — 1 tsp per bowl, for finishing',
      'Chili oil — to taste',
    ],
    equipment: ['Stock pot', 'Mesh strainer'],
    subs: [
      ['Soy milk', 'Cashew cream thinned with water (soy-free)'],
      ['Ramen noodles', 'Rice ramen noodles (gluten-free)'],
      ['Miso', 'Chickpea miso (soy-free)'],
      ['Marinated tofu', 'King oyster "chashu" (soy-free)'],
    ],
    steps: [
      'Combine kombu and dried shiitake in cold water; steep overnight in refrigerator for dashi.',
      'Strain dashi; discard kombu; slice reconstituted shiitakes for garnish.',
      'Warm dashi over low heat; whisk in soy milk, sesame paste, miso tare, and soy sauce until smooth.',
      'Bring broth to a gentle simmer; do NOT boil (soy milk splits above 190°F).',
      'Cook ramen noodles in separate boiling water per package; drain and rinse.',
      'Portion noodles into warmed bowls; ladle hot broth generously over.',
      'Arrange marinated tofu slices, sliced shiitakes, scallion, and nori.',
      'Finish each bowl with 1 tsp mayu and chili oil to taste; serve at once.',
    ],
    badge: 'Broth-forward',
  },
  {
    id: 'r13',
    title: 'Massaman Beef Curry (ปราศจากการทารุณกรรม)',
    source: 'Soy curls & potato',
    cuisine: 'thai', cuisineName: 'Thai',
    photo: 'bowl', photoLabel: 'curry · peanut · cardamom',
    why: 'Toasted spice paste freezes in batches; soy curls absorb 30 minutes of simmering coconut.',
    prep: '40m', serves: 4, difficulty: 2, cost: 3.40,
    ingredients: [
      'Soy curls — 150g dry, rehydrated in warm water',
      'Yukon Gold potato — 3 medium, peeled and cut into 1.5-in chunks',
      'Full-fat coconut milk — 1 can (400ml)',
      'Massaman curry paste — 3 tbsp (store-bought or house-made)',
      'Dry-roasted peanuts — 1/2 cup, roughly chopped, plus extra for garnish',
      'Yellow onion — 1 medium, cut into wedges',
      'Palm sugar — 1 tbsp (or brown sugar)',
      'Tamarind paste — 1 tbsp',
      'Soy sauce — 1 tbsp',
      'Cinnamon stick — 1',
      'Cardamom pods — 3, lightly crushed',
      'Bay leaf — 2',
      'Vegetable stock — 1 cup',
      'Jasmine rice — 2 cups, cooked, for service',
    ],
    equipment: ['Heavy pot', 'Mortar'],
    subs: [
      ['Soy curls', 'Jackfruit (soy-free)'],
      ['Peanut', 'Cashew (same method)'],
      ['Peanut', 'Toasted pumpkin seed (nut-free)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
      ['Coconut milk', 'Oat cream (coconut-free)'],
    ],
    steps: [
      'Fry massaman paste in 2 tbsp of the thick coconut cream from the top of the can 3 min until fragrant.',
      'Add remaining coconut milk, stock, cinnamon, cardamom, and bay leaf; bring to a simmer.',
      'Add potato and onion; cook 15 min until potatoes are almost tender.',
      'Add rehydrated soy curls, peanuts, palm sugar, tamarind, and soy sauce.',
      'Simmer 15 min until curls are saturated and sauce has thickened slightly.',
      'Taste for sweet-sour-salt balance; adjust tamarind and palm sugar.',
      'Remove whole spices; ladle over jasmine rice; garnish with extra peanuts.',
    ],
    badge: 'Aromatic',
  },
  {
    id: 'r13b',
    title: 'Som Tam · Green Papaya Salad',
    cuisine: 'thai', cuisineName: 'Thai',
    photo: 'flat', photoLabel: 'papaya · lime · chile',
    why: 'Pounded to order in the mortar; bright, crunchy, naturally plant-based. 4-minute counter dish.',
    prep: '10m', serves: 2, difficulty: 1, cost: 1.80,
    ingredients: [
      'Green papaya — 1 small (about 400g), peeled and julienned or shredded',
      'Lime — 2, juiced (about 4 tbsp)',
      'Bird\'s eye chile — 2–4, depending on heat level, pounded',
      'Long beans — 6, cut into 1.5-in pieces',
      'Cherry tomatoes — 6, halved',
      'Dry-roasted peanuts — 3 tbsp, roughly pounded',
      'Coconut palm sugar — 1 tsp',
      'Soy sauce — 1 tsp (sub coconut aminos to avoid soy)',
      'Garlic — 1 clove, pounded with the chile',
      'Dried shrimp alternative (optional) — 1 tsp smoked nori flakes for umami',
    ],
    equipment: ['Mortar & pestle'],
    subs: [
      ['Peanut', 'Cashew (different crunch)'],
      ['Peanut', 'Toasted sunflower seeds (nut-free)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
      ['Green papaya', 'Green mango (seasonal swap)'],
    ],
    steps: [
      'Pound chile and garlic to a rough paste in the mortar; do not fully pulverize.',
      'Add long beans; pound 3–4 times to bruise but keep texture.',
      'Add tomatoes; pound 2 times just to split the skins.',
      'Add palm sugar, lime juice, and soy sauce; stir with a spoon to dissolve sugar.',
      'Add shredded papaya in batches; toss and pound gently until papaya wilts slightly.',
      'Fold in peanuts; taste for balance — should be sharp, sweet, salty, and spicy.',
      'Transfer to plates immediately; serve with sticky rice.',
    ],
    badge: 'Cold prep',
  },
  {
    id: 'r14',
    title: 'Pad Krapow Moo (ปราศจากการทารุณกรรม)',
    source: 'Crumbled tofu & mushroom',
    cuisine: 'thai', cuisineName: 'Thai',
    photo: 'flat', photoLabel: 'wok · basil · chile',
    why: 'High-heat wok sear with holy basil; six minutes start to finish, plates over jasmine rice.',
    prep: '15m', serves: 2, difficulty: 1, cost: 2.40,
    ingredients: [
      'Extra-firm tofu — 300g, pressed and crumbled coarsely',
      'King oyster mushrooms — 150g, diced',
      'Fresh holy basil (krapow) — 1 large bunch, leaves only',
      'Bird\'s eye chile — 3–5, sliced thin or pounded',
      'Garlic — 4 cloves, minced',
      'Soy sauce — 1 tbsp',
      'Dark soy sauce — 1 tsp (for color)',
      'Oyster sauce (vegan) — 1 tbsp',
      'Sugar — 1/2 tsp',
      'Neutral oil — 2 tbsp, for wok',
      'Jasmine rice — 2 cups cooked, for service',
      'Fried shallots — 2 tbsp, for garnish',
    ],
    equipment: ['Carbon-steel wok', 'High BTU burner'],
    subs: [
      ['Tofu', 'Soy curls (crumbled, same method)'],
      ['Tofu', 'Chickpea tofu / Burmese tofu (soy-free)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
      ['Vegan oyster sauce', 'Mushroom sauce (check GF label)'],
    ],
    steps: [
      'Heat wok on high heat until smoking; add oil and swirl to coat.',
      'Add garlic and chile; stir-fry 30 sec — do not let garlic burn.',
      'Add crumbled tofu; press against wok surface to develop color, 2 min undisturbed.',
      'Add diced king oyster; toss with tofu, stir-fry 1 min.',
      'Add soy sauce, dark soy, vegan oyster sauce, and sugar; toss to coat evenly.',
      'Add holy basil leaves off the heat; toss until just wilted.',
      'Plate over jasmine rice; top with fried shallots; serve immediately.',
    ],
    badge: 'Wok-fired',
  },
  {
    id: 'r15',
    title: 'Char Siu (Wú nüèdài)',
    source: 'Seitan · lacquered',
    cuisine: 'chinese', cuisineName: 'Chinese',
    photo: 'plate', photoLabel: 'lacquer · five-spice · char',
    why: 'Five-spice seitan glazed with hoisin-maltose; the lacquer crackles like real char siu under the broiler.',
    prep: '50m', serves: 6, difficulty: 2, cost: 3.10,
    ingredients: [
      'Seitan — 600g, formed into 3 even logs',
      'Hoisin sauce — 4 tbsp',
      'Maltose syrup — 2 tbsp (or golden syrup)',
      'Five-spice powder — 1 tsp',
      'Fermented red bean curd (nam yü) — 1 tbsp, mashed',
      'Soy sauce — 1 tbsp',
      'Shaoxing wine — 1 tbsp',
      'Garlic — 2 cloves, minced',
      'Ginger — 1-in piece, grated',
      'White pepper — 1/4 tsp',
      'Red food coloring or beet powder — 1/4 tsp (for authentic color)',
      'Sesame oil — 1 tsp, for finish',
      'Scallion — 2, for garnish',
    ],
    equipment: ['Broiler', 'Hooks or rack'],
    subs: [
      ['Seitan', 'King trumpet logs (gluten-free)'],
      ['Hoisin sauce', 'Tamari + plum sauce (check GF)'],
      ['Fermented bean curd', 'White miso (gluten-free check)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
    ],
    steps: [
      'Mix hoisin, maltose, five-spice, fermented bean curd, soy sauce, Shaoxing wine, garlic, ginger, and pepper.',
      'Coat seitan logs in marinade; refrigerate at least 2h or overnight.',
      'Hang or lay on a rack in an oven at 375°F; roast 20 min.',
      'Brush generously with remaining marinade; broil on high 5 min until lacquer blisters and chars.',
      'Rest 5 min; slice on a bias into 1/3-in pieces.',
      'Finish with a light drizzle of sesame oil and scatter scallion.',
      'Serve over steamed jasmine rice with mustard and hoisin on the side.',
    ],
    badge: 'Showpiece',
  },
  {
    id: 'r16',
    title: 'Kung Pao Chicken (Wú nüèdài)',
    source: 'Soy curls & peanut',
    cuisine: 'chinese', cuisineName: 'Chinese',
    photo: 'flat', photoLabel: 'wok · sichuan · peanut',
    why: 'Mala heat from Sichuan peppercorn, blistered chiles, soy curls. Eight minutes wok-fired.',
    prep: '20m', serves: 4, difficulty: 2, cost: 2.70,
    ingredients: [
      'Soy curls — 150g dry, rehydrated in warm stock 10 min',
      'Dry-roasted peanuts — 1/2 cup',
      'Sichuan peppercorn — 1 tsp, toasted and roughly ground',
      'Dried red chiles — 8–10, cut into 1-in pieces, seeds mostly in',
      'Chinese black vinegar (Chinkiang) — 1 tbsp',
      'Soy sauce — 2 tbsp',
      'Hoisin sauce — 1 tsp',
      'Shaoxing wine — 1 tbsp',
      'Sugar — 1 tsp',
      'Cornstarch — 1 tsp, dissolved in 2 tbsp water',
      'Scallion — 4, cut into 1-in pieces',
      'Garlic — 3 cloves, minced',
      'Fresh ginger — 1-in piece, minced',
      'Neutral oil — 3 tbsp',
    ],
    equipment: ['Wok'],
    subs: [
      ['Soy curls', 'Tempeh cubes (soy allergen note: tempeh is still soy)'],
      ['Soy curls', 'King oyster mushroom (soy-free)'],
      ['Peanut', 'Cashew (different flavor profile)'],
      ['Peanut', 'Toasted sunflower seeds (nut-free)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
    ],
    steps: [
      'Whisk soy sauce, black vinegar, Shaoxing wine, hoisin, sugar, and cornstarch slurry into a sauce.',
      'Heat wok on highest flame until smoking; add oil.',
      'Fry dried chiles and Sichuan peppercorn 30 sec until fragrant and starting to darken.',
      'Add garlic and ginger; stir-fry 20 sec.',
      'Add drained soy curls; press and toss 2 min until edges are caramelized.',
      'Add scallion pieces; toss 30 sec.',
      'Pour sauce over; toss rapidly 1 min until sauce thickens and coats everything.',
      'Fold in peanuts off the heat; plate immediately over steamed rice.',
    ],
    badge: 'Mala',
  },
  {
    id: 'r17',
    title: 'Lamb Shawarma (Bidun qaswa)',
    source: 'Seitan · spit-style',
    cuisine: 'middle-eastern', cuisineName: 'Middle Eastern',
    photo: 'flat', photoLabel: 'spit · spice · pita',
    why: 'Layered seitan stack roasts upright like a real spit; carved to order, plates with toum and pickle.',
    prep: '70m', serves: 8, difficulty: 3, cost: 3.80,
    ingredients: [
      'Seitan — 1 kg, formed into thin steaks and layered on a vertical skewer or roasting rack',
      'Baharat spice blend — 3 tbsp (allspice, cinnamon, cumin, coriander, paprika, black pepper)',
      'Pita bread — 8 rounds, for service',
      'Toum (garlic sauce) — 1 cup (garlic, oil, lemon, salt, emulsified by blender)',
      'Sumac-marinated red onion — 2 onions, thinly sliced, tossed with 1 tbsp sumac',
      'Turmeric — 1 tsp',
      'Lemon juice — 3 tbsp',
      'Olive oil — 4 tbsp, for marinade',
      'Garlic — 4 cloves, minced, for marinade',
      'Cucumber pickles — 1 cup sliced, for service',
      'Fresh flat-leaf parsley — 1/2 cup, chopped, for service',
      'Tomato — 2, sliced, for service',
    ],
    equipment: ['Vertical roaster or oven', 'Mandoline'],
    subs: [
      ['Seitan', 'King oyster mushroom stacked (gluten-free)'],
      ['Pita', 'Gluten-free flatbread (gluten-free)'],
    ],
    steps: [
      'Mix baharat, turmeric, lemon, olive oil, and garlic into a marinade paste.',
      'Coat seitan steaks thoroughly; stack tightly on vertical skewer or tightly on a rack.',
      'Roast in oven at 425°F for 30 min until exterior is deeply browned.',
      'Rotate or flip the stack; roast another 20 min for even caramelization.',
      'Carve thin slices off the outer surface with a sharp knife to order.',
      'Warm pitas on the griddle 30 sec per side; spread generously with toum.',
      'Layer with shawarma, sumac onion, tomato, cucumber pickle, and parsley.',
      'Wrap tightly and serve immediately, or plate open-face for the table.',
    ],
    badge: 'Plate-forward',
  },
  {
    id: 'r18',
    title: 'Lamb Kibbeh (Bidun qaswa)',
    source: 'Lentil & walnut',
    cuisine: 'middle-eastern', cuisineName: 'Middle Eastern',
    photo: 'plate', photoLabel: 'kibbeh · pomegranate · mint',
    why: 'Lentil-walnut filling holds the shape of classic kibbeh; fries to a clean shell, plates with tahini.',
    prep: '50m', serves: 8, difficulty: 2, cost: 1.90,
    ingredients: [
      'Brown lentils — 1 cup, cooked and drained',
      'Walnuts — 1 cup, toasted and roughly chopped',
      'Fine bulgur wheat — 1 cup, soaked in cold water 20 min, squeezed dry',
      'Allspice — 1.5 tsp, ground',
      'Cinnamon — 1/2 tsp, ground',
      'Yellow onion — 2, finely diced (1 for shell, 1 for filling)',
      'Pine nuts — 3 tbsp, toasted',
      'Fresh mint — 3 tbsp, chopped',
      'Pomegranate molasses — 1 tbsp, for filling',
      'Tahini — 1/2 cup, for dipping sauce',
      'Lemon — 1, juiced, for tahini sauce',
      'Olive oil — 2 tbsp, for sautéing filling',
      'Neutral oil — for deep-frying',
      'Salt and black pepper — to taste',
    ],
    equipment: ['Food processor', 'Fryer'],
    subs: [
      ['Walnut', 'Pumpkin seed (nut-free)'],
      ['Pine nuts', 'Sunflower seeds (nut-free)'],
      ['Bulgur wheat', 'Quinoa (gluten-free)'],
    ],
    steps: [
      'Process cooked lentils with half the onion, half the allspice, cinnamon, and bulgur until a smooth, pliable dough forms.',
      'Season shell dough with salt; refrigerate 20 min to firm up.',
      'Sauté remaining onion in olive oil 8 min; add toasted walnuts, pine nuts, remaining allspice.',
      'Stir in mint and pomegranate molasses; cook 2 min; cool filling completely.',
      'Wet hands; form shell dough into oval; hollow with a finger; fill with walnut mixture; seal and shape.',
      'Refrigerate assembled kibbeh 15 min; deep-fry at 350°F for 3–4 min until deep mahogany.',
      'Drain on rack; season with salt immediately.',
      'Whisk tahini with lemon juice and water to a pourable sauce; serve alongside.',
    ],
    badge: 'High-margin',
  },
  {
    id: 'r19',
    title: 'Paella de Marisc (Chorís sklirótita)',
    source: 'Hearts of palm & oyster mushroom',
    cuisine: 'mediterranean', cuisineName: 'Mediterranean',
    photo: 'flat', photoLabel: 'saffron · socarrat · paella',
    why: 'Hearts of palm read as squid rings; oyster mushrooms as scallops. Socarrat is real either way.',
    prep: '45m', serves: 6, difficulty: 2, cost: 4.10,
    ingredients: [
      'Bomba rice — 2 cups (or Arborio if unavailable)',
      'Hearts of palm — 300g, sliced into rings',
      'Oyster mushrooms — 300g, torn into large pieces',
      'Saffron — 1 generous pinch (about 1/4 tsp), bloomed in 2 tbsp warm water',
      'Smoked paprika — 2 tsp',
      'Vegetable stock — 5 cups, kept hot',
      'Crushed tomato — 1/2 cup',
      'Yellow onion — 1, finely diced',
      'Red bell pepper — 1, sliced',
      'Garlic — 4 cloves, minced',
      'Olive oil — 4 tbsp',
      'Lemon — 2, cut into wedges, for service',
      'Flat-leaf parsley — 3 tbsp, chopped, for garnish',
      'Frozen peas — 1/2 cup (added last 5 min)',
    ],
    equipment: ['Paella pan', 'High-BTU burner'],
    subs: [
      ['Hearts of palm', 'King trumpet rounds (meatier)'],
      ['Oyster mushrooms', 'King oyster scallop-cut'],
      ['Bomba rice', 'Calasparra rice (same method)'],
    ],
    steps: [
      'Heat paella pan on high BTU burner; add olive oil; sear mushrooms 3 min until golden, remove.',
      'In same pan, sauté onion and pepper 5 min; add garlic and smoked paprika, cook 1 min.',
      'Add crushed tomato (sofrito); cook down 5 min until nearly dry.',
      'Add bomba rice; stir to coat in sofrito 2 min to toast.',
      'Pour in all hot stock and saffron water at once; shake to level; do not stir again.',
      'Add hearts of palm rings and seared mushrooms; distribute evenly.',
      'Cook on medium-high 15 min until rice is almost tender and stock nearly absorbed.',
      'Scatter peas; raise heat to high for final 2 min to develop the socarrat crust.',
      'Remove from heat; rest 5 min uncovered; garnish with parsley and lemon wedges.',
    ],
    badge: 'Tableside',
  },
  {
    id: 'r19b',
    title: 'Mujadara · Lentil & Caramelized Onion',
    cuisine: 'middle-eastern', cuisineName: 'Middle Eastern',
    photo: 'layered', photoLabel: 'lentil · rice · onion',
    why: 'One-pot lentil-rice; deeply caramelized onion is the only garnish. Naturally plant-based, high-margin.',
    prep: '50m', serves: 8, difficulty: 1, cost: 1.45,
    ingredients: [
      'Brown or green lentils — 1.5 cups',
      'Basmati rice — 1 cup, rinsed',
      'Yellow onion — 4 large, thinly sliced (for caramelizing)',
      'Cumin — 2 tsp, ground',
      'Coriander — 1 tsp, ground',
      'Cinnamon — 1/4 tsp, ground',
      'Olive oil — 1/3 cup (split: 3 tbsp for onions, rest for pot)',
      'Water or vegetable stock — 4 cups',
      'Salt — 1.5 tsp',
      'Black pepper — 1/2 tsp',
      'Lemon juice — 2 tbsp, for finish',
      'Greek-style coconut yogurt — optional, for serving',
    ],
    equipment: ['Heavy pot', 'Wide skillet'],
    subs: [
      ['Basmati', 'Long-grain white rice (same ratio)'],
      ['Coconut yogurt', 'Cashew yogurt (coconut-free)'],
    ],
    steps: [
      'Caramelize sliced onion in 3 tbsp olive oil over medium-low heat 30–35 min, stirring often, until deep amber.',
      'Meanwhile, simmer lentils in stock 15 min until just tender; drain, reserving 3 cups liquid.',
      'In heavy pot, heat remaining oil; add cumin, coriander, cinnamon — bloom 30 sec.',
      'Add lentils and rice; stir to coat in spiced oil.',
      'Pour reserved lentil liquid plus enough water to reach 3 cups total; bring to a boil.',
      'Cover tightly; reduce to lowest heat; cook 18 min until rice is tender.',
      'Remove lid; fluff gently; season with salt, pepper, and lemon juice.',
      'Top generously with caramelized onion at service; offer yogurt on the side.',
    ],
    badge: 'High-margin',
  },
  {
    id: 'r20',
    title: 'Souvlaki (Chorís sklirótita)',
    source: 'Marinated seitan',
    cuisine: 'mediterranean', cuisineName: 'Mediterranean',
    photo: 'flat', photoLabel: 'skewer · oregano · lemon',
    why: 'Hard char on the grill; tzatziki holds 3 days. Plate with pita, tomato, oregano. 12-min line build.',
    prep: '25m', serves: 4, difficulty: 1, cost: 3.20,
    ingredients: [
      'Seitan — 500g, cut into 1.5-in cubes',
      'Dried oregano — 2 tsp',
      'Lemon — 2, juiced (about 6 tbsp) and zested',
      'Olive oil — 4 tbsp',
      'Garlic — 3 cloves, minced',
      'Cashew tzatziki — 1 cup (soaked cashews, cucumber, dill, lemon, garlic, blended)',
      'Pita bread — 4 rounds',
      'Tomato — 2, sliced',
      'Red onion — 1, thinly sliced',
      'Fresh parsley — 2 tbsp, chopped',
      'Paprika — 1/2 tsp',
      'Salt and black pepper — to taste',
    ],
    equipment: ['Grill', 'Skewers'],
    subs: [
      ['Seitan', 'King trumpet (gluten-free)'],
      ['Cashew tzatziki', 'Sunflower-seed tzatziki (nut-free)'],
      ['Pita', 'Gluten-free flatbread (gluten-free)'],
    ],
    steps: [
      'Marinate seitan cubes in olive oil, lemon juice, zest, oregano, garlic, paprika, salt at least 1h.',
      'Thread onto metal skewers, 4–5 pieces per skewer, leaving small gaps.',
      'Grill on high heat 3 min per side, 4 sides total, until hard char marks form.',
      'Rest skewers 2 min off heat; do not cover (steam softens the char).',
      'Warm pitas on the grill 30 sec per side.',
      'Spread tzatziki generously on pita; lay souvlaki alongside.',
      'Top with sliced tomato, red onion, and parsley; serve with lemon wedge.',
    ],
    badge: 'Quick-fire',
  },
  {
    id: 'r21',
    title: 'Smoked Brisket (No Cruelty)',
    source: 'Tempeh · 4h smoked',
    cuisine: 'american', cuisineName: 'American',
    photo: 'layered', photoLabel: 'bark · smoke ring · slice',
    why: 'Tempeh slabs build a real bark in 4 hours of low smoke; develops pink ring with curing salt.',
    prep: '4h', serves: 8, difficulty: 3, cost: 4.40,
    ingredients: [
      'Tempeh — 1 kg, in 2 large slabs (steamed 10 min first to remove bitterness)',
      'Smoked paprika — 2 tbsp',
      'Curing salt (pink salt #1) — 1/4 tsp (for smoke ring effect)',
      'Fine ground coffee — 2 tbsp',
      'Brown sugar — 2 tbsp',
      'Coarse black pepper — 2 tsp',
      'Garlic powder — 1 tsp',
      'Onion powder — 1 tsp',
      'Cayenne — 1/2 tsp',
      'Mustard (yellow) — 2 tbsp, as binder',
      'Apple cider vinegar — 4 tbsp, for spritz during smoke',
      'Vegan worcestershire — 1 tbsp, in spritz',
      'Oak or hickory wood chips — 2 cups, for smoker',
      'Brisket-style BBQ sauce — 1 cup, for serving',
    ],
    equipment: ['Smoker', 'Probe thermometer'],
    subs: [
      ['Tempeh', 'King oyster slab (soy-free)'],
      ['Tempeh', 'Seitan roast (gluten note)'],
    ],
    steps: [
      'Steam tempeh slabs 10 min; cool; brush surfaces with yellow mustard as a binder.',
      'Mix dry rub: paprika, coffee, brown sugar, pepper, garlic, onion, cayenne, curing salt.',
      'Coat slabs on all sides with rub; let rest uncovered in refrigerator 1h to form pellicle.',
      'Set smoker to 225°F with oak or hickory; place tempeh fat-side-up on grates.',
      'Smoke 4h, spritzing with apple cider vinegar and worcestershire every 45 min.',
      'Internal temp should read 165°F; bark should be dark mahogany and dry to touch.',
      'Rest 20 min loosely tented in foil; do not wrap tightly (softens bark).',
      'Slice against the grain in 1/4-in planks; plate with BBQ sauce and pickled jalapeños.',
    ],
    badge: 'Customer favorite',
  },
  {
    id: 'r22',
    title: 'Ribeye Plate (No Cruelty)',
    source: 'Wheat-protein steak · marbled',
    cuisine: 'american', cuisineName: 'American',
    photo: 'plate', photoLabel: 'sear · grain · jus',
    why: 'Laminated wheat protein with beet-marbling; sears with a real crust. Plate with roasted bone-marrow oil.',
    prep: '30m', serves: 2, difficulty: 3, cost: 5.40,
    ingredients: [
      'Vital wheat gluten — 200g',
      'Beet — 1 small, roasted and puréed (for fat-streak effect)',
      'Mushroom stock — 1/2 cup, warm, for kneading dough',
      'Soy sauce — 1 tbsp',
      'Nutritional yeast — 2 tbsp',
      'Black pepper — 1 tsp, coarsely cracked',
      'Garlic powder — 1/2 tsp',
      'Bone-marrow oil (vegan) — 2 tbsp (roasted bone-shaped medjool date + refined coconut oil, blended)',
      'Vegan butter — 2 tbsp, for basting',
      'Fresh thyme — 3 sprigs',
      'Garlic — 2 cloves, crushed',
      'Fleur de sel — to taste',
      'Roasted potato wedges — for service',
    ],
    equipment: ['Cast iron', 'Steamer'],
    subs: [
      ['Wheat protein', 'Layered king oyster slab (gluten-free)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
      ['Coconut oil in marrow oil', 'Refined avocado oil (coconut-free)'],
    ],
    steps: [
      'Mix vital wheat gluten with nutritional yeast, garlic powder, soy sauce, and warm stock into a stiff dough.',
      'Knead 5 min; divide into 2 steaks; marble beet purée through by layering and folding.',
      'Shape each steak; steam 20 min until firm; cool to room temperature.',
      'Season aggressively with black pepper and salt; let rest uncovered 10 min.',
      'Heat cast iron until smoking; add neutral oil; sear steaks 3 min per side without moving.',
      'Add vegan butter, thyme, and garlic; baste continuously for 2 min.',
      'Rest on a wire rack 5 min; drizzle with bone-marrow oil at the pass.',
      'Plate with roasted potato wedges; finish with fleur de sel and cracked pepper.',
    ],
    badge: 'Fine-dining',
  },
  {
    id: 'r23',
    title: 'Korean Hotpot · Budae Jjigae (동물 학대 없음)',
    source: 'Seitan sausage & tofu',
    cuisine: 'korean', cuisineName: 'Korean',
    photo: 'bowl', photoLabel: 'hotpot · gochujang · ramyeon',
    why: 'Army-stew base with seitan sausage and tofu; tabletop simmer is the show. Broth holds in service well.',
    prep: '35m', serves: 4, difficulty: 1, cost: 3.60,
    ingredients: [
      'Seitan sausage — 300g, sliced into 1/2-in rounds',
      'Firm tofu — 300g, sliced into 1/2-in slabs',
      'Gochujang — 3 tbsp',
      'Kimchi — 1 cup, roughly chopped (vegan kimchi)',
      'Ramyeon (instant noodles) — 2 packs, noodles only',
      'Vegetable stock — 4 cups',
      'Dried shiitake — 4, soaked and sliced',
      'Garlic — 3 cloves, minced',
      'Gochugaru (Korean chili flakes) — 1 tbsp',
      'Soy sauce — 2 tbsp',
      'Sesame oil — 1 tsp, for finish',
      'Scallion — 3, cut into 1-in pieces',
      'Vegan American-style "cheese" slice — 2 (optional, for the authentic budae note)',
    ],
    equipment: ['Tabletop burner', 'Earthenware pot'],
    subs: [
      ['Seitan sausage', 'Mushroom medley (gluten-free)'],
      ['Firm tofu', 'Chickpea tofu / Burmese tofu (soy-free)'],
      ['Ramyeon', 'Rice ramyeon / glass noodles (gluten-free)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
    ],
    steps: [
      'Arrange seitan sausage, tofu, kimchi, and shiitakes in sections in the earthenware pot.',
      'Whisk gochujang, gochugaru, garlic, and soy sauce into stock; pour over ingredients.',
      'Bring to a boil on the tabletop burner in front of guests.',
      'Add ramyeon noodles; simmer 3 min until noodles are just cooked.',
      'Lay optional vegan cheese on top; allow to melt into the broth.',
      'Finish with sesame oil and scallion; serve directly from the pot family-style.',
    ],
    badge: 'Tableside',
  },
  {
    id: 'r24',
    title: 'Galbi Short Rib (동물 학대 없음)',
    source: 'King trumpet · scored',
    cuisine: 'korean', cuisineName: 'Korean',
    photo: 'flat', photoLabel: 'galbi · pear · sesame',
    why: 'Asian-pear marinade tenderizes scored king trumpet; sears in 90 seconds, eats like short rib.',
    prep: '30m', serves: 4, difficulty: 2, cost: 3.80,
    ingredients: [
      'King trumpet mushrooms — 8 large, halved lengthwise, scored bone-in galbi style',
      'Asian pear — 1, grated (about 1/2 cup)',
      'Soy sauce — 4 tbsp',
      'Sesame oil — 2 tbsp',
      'Toasted sesame seeds — 1 tbsp, plus extra for garnish',
      'Garlic — 4 cloves, minced',
      'Fresh ginger — 1-in piece, grated',
      'Brown sugar — 2 tbsp',
      'Scallion — 3, thinly sliced, for garnish',
      'Gochugaru — 1/2 tsp, for a hint of heat',
      'Neutral oil — 1 tbsp, for searing',
      'Steamed jasmine or short-grain rice — for service',
      'Perilla leaves — 4, for garnish (optional)',
    ],
    equipment: ['Tabletop grill or cast iron'],
    subs: [
      ['King trumpet', 'Tempeh sliced thick (soy allergen note)'],
      ['Soy sauce', 'Tamari (gluten-free)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
    ],
    steps: [
      'Mix grated pear, soy sauce, sesame oil, garlic, ginger, brown sugar, and gochugaru.',
      'Score the flat face of each king trumpet half in crosshatch pattern, 1/4-in deep.',
      'Marinate scored mushrooms in pear mixture at least 30 min (or overnight).',
      'Heat cast iron or tabletop grill to high; add neutral oil.',
      'Sear mushrooms scored-side down 90 sec until caramelized and aromatic.',
      'Flip; cook 60 sec on other side; brush with remaining marinade.',
      'Plate over steamed rice; garnish with sesame seeds, scallion, and perilla.',
    ],
    badge: 'Interactive',
  },
  {
    id: 'r25',
    title: 'Phở Bò (Không ngược đãi)',
    source: 'Charred onion broth & soy curls',
    cuisine: 'vietnamese', cuisineName: 'Vietnamese',
    photo: 'bowl', photoLabel: 'pho · star anise · basil',
    why: 'Charred onion-ginger broth with a 6-spice tea infusion gets the savory depth. Soy curls slice in.',
    prep: '60m', serves: 6, difficulty: 2, cost: 3.10,
    ingredients: [
      'Soy curls — 180g dry, rehydrated in warm water',
      'Star anise — 4 whole',
      'Cinnamon stick — 2-in piece',
      'Cloves — 4 whole',
      'Black cardamom — 1 pod',
      'Coriander seeds — 1 tsp, toasted',
      'Fennel seeds — 1/2 tsp, toasted',
      'Yellow onion — 2 large, halved and charred cut-side down under broiler',
      'Fresh ginger — 3-in piece, halved and charred',
      'Rock sugar — 1 tbsp (or 2 tsp brown sugar)',
      'Soy sauce — 3 tbsp, for broth seasoning',
      'Rice noodles (bánh phở) — 500g, soaked and drained',
      'Fresh Thai basil — 1 bunch, for service',
      'Bean sprouts — 200g, for service',
      'Lime — 3, cut into wedges, for service',
      'Hoisin sauce and sriracha — for table condiments',
    ],
    equipment: ['Stock pot', 'Mesh strainer'],
    subs: [
      ['Soy curls', 'King oyster sliced thin (soy-free)'],
      ['Soy sauce', 'Coconut aminos (soy-free)'],
      ['Rice noodles', 'Sweet potato noodles (grain-free option)'],
    ],
    steps: [
      'Char onion halves and ginger under broiler 10–12 min until blackened in spots; set aside.',
      'Toast whole spices in dry pot 1 min until fragrant; add 8 cups water, charred onion, and ginger.',
      'Bring to a boil; reduce to a gentle simmer; cook 40 min uncovered.',
      'Add rock sugar and soy sauce; simmer 5 more min.',
      'Strain through mesh strainer; discard solids; adjust seasoning of clear broth.',
      'Blanch rehydrated soy curls in broth 2 min; remove and slice thin on a bias.',
      'Portion soaked rice noodles into warmed bowls; top with sliced soy curls.',
      'Ladle boiling hot broth over noodles; serve with herb plate and condiments.',
    ],
    badge: 'Lunch hero',
  },
  {
    id: 'r26',
    title: 'Jamaican Jerk Chicken (No Cruelty)',
    source: 'King oyster & jackfruit',
    cuisine: 'caribbean', cuisineName: 'Caribbean',
    photo: 'flat', photoLabel: 'jerk · pimento · lime',
    why: 'Pimento-wood smoke on king oyster "drumsticks"; jerk paste keeps two weeks for service.',
    prep: '40m', serves: 6, difficulty: 2, cost: 3.50,
    ingredients: [
      'King oyster mushrooms — 600g, halved lengthwise ("drumstick" shaped)',
      'Young jackfruit (canned) — 1 can (400g), drained and shredded',
      'Scotch bonnet chiles — 3 (or habanero), stemmed',
      'Whole allspice berries — 1 tbsp',
      'Fresh thyme — 1 tbsp leaves',
      'Garlic — 4 cloves',
      'Fresh ginger — 1-in piece',
      'Scallion — 4',
      'Dark soy sauce — 1 tbsp',
      'Brown sugar — 1 tbsp',
      'Lime juice — 3 tbsp',
      'Neutral oil — 2 tbsp',
      'Cooked rice and peas — for service',
      'Sliced fresh pineapple — for service',
    ],
    equipment: ['Grill', 'Heavy pot'],
    subs: [
      ['King oyster', 'Tempeh (soy allergen note)'],
      ['King oyster', 'Seitan (gluten allergen note)'],
      ['Dark soy sauce', 'Coconut aminos (soy-free)'],
    ],
    steps: [
      'Blend scotch bonnet, allspice, thyme, garlic, ginger, scallion, soy sauce, sugar, and lime into jerk paste.',
      'Toss king oyster mushrooms and jackfruit thoroughly in jerk paste; marinate 1h minimum.',
      'Slow-cook jackfruit in heavy pot with 1/2 cup water 20 min until falling apart.',
      'Grill king oyster on high heat 3 min per side until charred and lacquered.',
      'Combine grilled mushrooms with pulled jackfruit on the plate.',
      'Drizzle with remaining jerk paste thinned with lime juice.',
      'Serve with rice and peas and fresh pineapple slices.',
    ],
    badge: 'Bold',
  },
  {
    id: 'r27',
    title: 'Doro Wat (Yale gif)',
    source: 'Soy curls & berbere',
    cuisine: 'ethiopian', cuisineName: 'Ethiopian',
    photo: 'plate', photoLabel: 'berbere · injera · onion',
    why: 'Slow-cooked with deeply caramelized onion and berbere; injera tears at the table.',
    prep: '70m', serves: 6, difficulty: 2, cost: 2.40,
    ingredients: [
      'Soy curls — 200g dry, rehydrated in warm water',
      'Berbere spice blend — 3 tbsp',
      'Yellow onion — 4 large, finely diced',
      'Injera — 6 pieces, for service',
      'Vegan niter kibbeh — 4 tbsp (vegan butter clarified with onion, garlic, ginger, and spices)',
      'Garlic — 4 cloves, minced',
      'Fresh ginger — 1.5-in piece, grated',
      'Tomato paste — 1 tbsp',
      'Dry red wine — 1/4 cup',
      'Vegetable stock — 1 cup',
      'Salt — to taste',
      'Fresh jalapeño — 1, sliced, for garnish (optional)',
    ],
    equipment: ['Heavy pot', 'Crepe pan'],
    subs: [
      ['Soy curls', 'Cremini mushroom quartered (soy-free)'],
      ['Soy curls', 'King trumpet (soy-free)'],
      ['Vegan niter kibbeh', 'Olive oil + turmeric + cumin (simplified)'],
    ],
    steps: [
      'Dry-sauté finely diced onion in heavy pot with no oil 15 min, stirring frequently, until very soft.',
      'Add vegan niter kibbeh; continue cooking onion 10 more min until deep caramel.',
      'Add garlic, ginger, and berbere; stir vigorously 3 min — this is the base of the wat.',
      'Add tomato paste; cook 2 min until paste is brick-red.',
      'Deglaze with red wine; reduce by half.',
      'Add rehydrated soy curls and stock; simmer covered 30 min.',
      'Uncover; reduce until sauce is thick enough to coat a spoon; adjust salt.',
      'Serve mounded on injera; tear injera at the table for communal scooping.',
    ],
    badge: 'Experiential',
  },
  {
    id: 'r27b',
    title: 'Misir Wat · Berbere Lentil Stew',
    cuisine: 'ethiopian', cuisineName: 'Ethiopian',
    photo: 'plate', photoLabel: 'lentil · berbere · injera',
    why: 'Slow-cooked red lentils with berbere; injera tears at the table. Naturally plant-based.',
    prep: '60m', serves: 6, difficulty: 2, cost: 2.20,
    ingredients: [
      'Red lentils — 2 cups, rinsed',
      'Berbere spice blend — 2.5 tbsp',
      'Yellow onion — 3 large, finely diced',
      'Injera — 6 pieces, for service',
      'Vegan niter kibbeh — 3 tbsp',
      'Garlic — 4 cloves, minced',
      'Fresh ginger — 1-in piece, grated',
      'Tomato paste — 1 tbsp',
      'Vegetable stock — 3 cups',
      'Lemon juice — 1 tbsp, for brightness at finish',
      'Salt — to taste',
    ],
    equipment: ['Heavy pot', 'Crepe pan'],
    subs: [
      ['Vegan niter kibbeh', 'Olive oil + spices (simplified, coconut-free)'],
      ['Red lentils', 'Split yellow peas (similar treatment)'],
    ],
    steps: [
      'Dry-sauté finely diced onion with no oil 10 min until soft; add niter kibbeh.',
      'Continue cooking onion in fat 8 min until deeply golden.',
      'Add garlic, ginger, and berbere; cook 3 min, stirring constantly.',
      'Add tomato paste; cook out 2 min.',
      'Add rinsed red lentils and stock; bring to a boil.',
      'Reduce heat; simmer 25–30 min until lentils completely dissolve into a thick stew.',
      'Adjust consistency with water or stock; season with salt and lemon juice.',
      'Serve on injera with a mound in the center; garnish with a drizzle of niter kibbeh.',
    ],
    badge: 'Experiential',
  },
  {
    id: 'r28',
    title: 'Chorizo a la Sidra (Sin crueldad)',
    source: 'Smoked seitan',
    cuisine: 'spanish', cuisineName: 'Spanish',
    photo: 'plate', photoLabel: 'chorizo · cider · smoke',
    why: 'Smoked seitan chorizo flamed in hard cider tableside; tapas-bar theater, two-minute service.',
    prep: '30m', serves: 4, difficulty: 1, cost: 3.10,
    ingredients: [
      'Seitan — 400g, shaped into 8 small links or thick rounds',
      'Smoked paprika (pimentón de la Vera) — 2 tsp',
      'Hard cider (sidra) — 1/2 cup',
      'Garlic — 3 cloves, thinly sliced',
      'Bay leaf — 2',
      'Olive oil — 2 tbsp',
      'Dried oregano — 1/2 tsp',
      'Cayenne — pinch',
      'Salt and black pepper — to taste',
      'Crusty sourdough or bread — for service',
      'Flat-leaf parsley — 1 tbsp, chopped, for garnish',
    ],
    equipment: ['Cast iron', 'Long matches'],
    subs: [
      ['Seitan', 'King trumpet rounds (gluten-free)'],
      ['Hard cider', 'Dry apple juice + 1 tsp apple cider vinegar (alcohol-free)'],
      ['Sourdough', 'Gluten-free crusty bread (gluten-free)'],
    ],
    steps: [
      'Score seitan links on two sides; season with smoked paprika, oregano, cayenne, salt, and pepper.',
      'Heat cast iron over medium-high; add olive oil; sear links 2 min per side until browned.',
      'Add sliced garlic; sauté 30 sec around the links.',
      'Add bay leaf; pour hard cider into the pan — it will sizzle aggressively.',
      'Simmer cider down by half, about 2 min, basting links.',
      'Flame tableside with long matches for theatrical effect; let flames die naturally.',
      'Finish with chopped parsley; serve in the cast iron with bread for sauce-mopping.',
    ],
    badge: 'Tableside',
  },
  {
    id: 'r29',
    title: 'Albóndigas (Sin crueldad)',
    source: 'Lentil & mushroom',
    cuisine: 'spanish', cuisineName: 'Spanish',
    photo: 'bowl', photoLabel: 'meatball · tomato · sherry',
    why: 'Lentil-mushroom meatballs hold their shape in the sherry-tomato sauce; freezer-friendly batch of 100.',
    prep: '45m', serves: 8, difficulty: 1, cost: 1.80,
    ingredients: [
      'Brown lentils — 1.5 cups, cooked and cooled',
      'Cremini mushrooms — 300g, finely chopped and sautéed dry',
      'Dry sherry (fino or amontillado) — 1/2 cup',
      'Crushed tomato — 1 can (400g)',
      'Smoked paprika — 2 tsp',
      'Breadcrumbs — 1/2 cup',
      'Flaxseed meal — 2 tbsp + 6 tbsp water (egg replacement)',
      'Garlic — 4 cloves (2 minced for balls, 2 for sauce)',
      'Yellow onion — 1, finely diced (half for balls, half for sauce)',
      'Fresh flat-leaf parsley — 3 tbsp, chopped',
      'Olive oil — 3 tbsp',
      'Cumin — 1 tsp',
      'Salt and black pepper — to taste',
      'Fresh mint — 1 tbsp, for finish',
    ],
    equipment: ['Food processor', 'Heavy pot'],
    subs: [
      ['Brown lentil', 'Black bean (different texture, bolder flavor)'],
      ['Breadcrumbs', 'Gluten-free breadcrumbs (gluten-free)'],
    ],
    steps: [
      'Mix flaxseed meal with water; rest 10 min until gel forms.',
      'Pulse lentils and sautéed mushrooms in food processor 5 times — chunky, not purée.',
      'Combine with breadcrumbs, flax egg, garlic, onion, smoked paprika, cumin, parsley, salt.',
      'Roll into 30g balls; refrigerate 15 min to firm.',
      'Pan-fry albóndigas in olive oil 5 min, turning to brown on 3 sides; remove.',
      'In same pot, sauté remaining onion and garlic 5 min; add sherry, reduce by half.',
      'Add crushed tomato; simmer 10 min; return albóndigas to sauce.',
      'Simmer gently 10 min; finish with fresh mint; serve in shallow bowls with crusty bread.',
    ],
    badge: 'Batch-cook',
  },
  {
    id: 'r30',
    title: 'Polpette al Sugo (Senza crudeltà)',
    source: 'Eggplant & breadcrumb',
    cuisine: 'italian', cuisineName: 'Italian',
    photo: 'bowl', photoLabel: 'meatball · sugo · basil',
    why: 'Roasted eggplant binds with breadcrumb and miso; tomato sugo holds 4 days. Margin king.',
    prep: '50m', serves: 8, difficulty: 1, cost: 1.50,
    ingredients: [
      'Globe eggplant — 2 large, roasted whole at 400°F until collapsed, flesh scooped',
      'Breadcrumbs (panko) — 1 cup',
      'White miso — 2 tbsp',
      'San Marzano tomatoes — 1 can (800g), crushed by hand',
      'Fresh basil — 1 large bunch',
      'Garlic — 5 cloves (2 for meatballs, 3 for sugo)',
      'Yellow onion — 1, finely diced, for sugo',
      'Olive oil — 4 tbsp',
      'Nutritional yeast — 2 tbsp',
      'Flaxseed meal — 2 tbsp + 6 tbsp water (egg replacement)',
      'Dried oregano — 1 tsp',
      'Chili flake — 1/4 tsp, for sugo',
      'Salt and black pepper — to taste',
      'Pasta (rigatoni or pappardelle) — 600g, cooked, for service (optional)',
    ],
    equipment: ['Sheet pan', 'Heavy pot'],
    subs: [
      ['Breadcrumb', 'Almond meal (gluten-free; introduces nut allergen)'],
      ['Breadcrumb', 'Gluten-free panko (gluten-free, nut-free)'],
      ['White miso', 'Chickpea miso (soy-free)'],
    ],
    steps: [
      'Roast whole eggplants at 400°F for 35–40 min until completely collapsed and steaming; cool.',
      'Scoop eggplant flesh; squeeze out excess liquid in a towel; chop roughly.',
      'Mix flaxseed meal with water; rest 10 min until gel forms.',
      'Combine eggplant, breadcrumbs, miso, nutritional yeast, garlic, oregano, flax egg, salt.',
      'Roll into 40g balls; arrange on oiled sheet pan; bake at 375°F for 20 min until golden.',
      'Sauté onion in olive oil 8 min; add garlic and chili flake; cook 2 min.',
      'Add crushed San Marzano; simmer 20 min until sugo deepens in color.',
      'Nestle baked polpette into sugo; simmer 5 min to marry; finish with torn basil.',
    ],
    badge: 'Margin king',
  },
  {
    id: 'r31',
    title: 'Cacio e Pepe',
    cuisine: 'italian', cuisineName: 'Italian',
    photo: 'plate', photoLabel: 'pasta · pepper · cream',
    why: 'Cashew cream emulsifies in 90 seconds; three pantry ingredients, restaurant-grade silk. Naturally plant-based.',
    prep: '20m', serves: 4, difficulty: 2, cost: 3.40,
    ingredients: [
      'Bucatini — 400g (or tonnarelli)',
      'Cashew cream — 1 cup (1 cup raw cashews soaked 4h, blended with 1/2 cup pasta water until silk)',
      'Black pepper — 2 tsp, very coarsely cracked; toasted in a dry pan',
      'Nutritional yeast — 4 tbsp (for the Pecorino/Parmesan note)',
      'Reserved pasta water — 1 cup minimum, kept near boiling',
      'Olive oil — 1 tbsp, for finishing',
      'Fleur de sel — to taste',
    ],
    equipment: ['Blender', 'Large pot', 'Heavy skillet'],
    subs: [
      ['Cashews', 'Sunflower seeds soaked (nut-free)'],
      ['Bucatini', 'Gluten-free spaghetti (gluten-free)'],
    ],
    steps: [
      'Toast cracked black pepper in dry skillet 1 min until fragrant; set aside.',
      'Cook bucatini in heavily salted water 2 min less than package time; reserve 1 cup pasta water before draining.',
      'Blend soaked cashews with 1/2 cup hot pasta water until completely smooth.',
      'Toss hot drained pasta in the skillet with toasted pepper and a splash of pasta water.',
      'Add cashew cream and nutritional yeast; toss vigorously 60–90 sec, adding pasta water to loosen.',
      'The sauce should coat each strand glossily without pooling.',
      'Plate immediately; finish with a turn of olive oil, extra cracked pepper, and fleur de sel.',
    ],
    badge: 'Crowd-pleaser',
  },
  {
    id: 'r32',
    title: 'Roasted Carrot, Tahini & Dukkah',
    cuisine: 'middle-eastern', cuisineName: 'Middle Eastern',
    photo: 'plate', photoLabel: 'carrot · tahini · sumac',
    why: 'Single sheet pan, three textures, plates like a magazine cover. Dukkah keeps for weeks.',
    prep: '40m', serves: 6, difficulty: 1, cost: 2.30,
    ingredients: [
      'Heritage carrots — 900g (mixed colors), scrubbed, halved lengthwise if large',
      'Tahini — 1/3 cup',
      'Lemon — 2, juiced',
      'Hazelnuts — 1/2 cup, toasted and skins rubbed off',
      'Coriander seeds — 2 tbsp, toasted',
      'Cumin seeds — 1 tbsp, toasted',
      'Sesame seeds — 2 tbsp, toasted',
      'Sumac — 1 tsp, for tahini sauce and garnish',
      'Olive oil — 3 tbsp, for roasting',
      'Honey alternative (agave) — 1 tbsp, for roasting glaze',
      'Smoked paprika — 1/4 tsp, for roasting',
      'Garlic — 1 clove, grated, for tahini sauce',
      'Ice water — 2–4 tbsp, to thin tahini sauce',
      'Micro herbs or parsley — for garnish',
    ],
    equipment: ['Sheet pan', 'Spice grinder'],
    subs: [
      ['Tahini', 'Sunflower butter (nut-free, also seed allergen note)'],
      ['Hazelnuts', 'Pumpkin seeds (nut-free dukkah)'],
    ],
    steps: [
      'Toss carrots with olive oil, agave, smoked paprika, and salt; spread on sheet pan without crowding.',
      'Roast at 425°F for 25–30 min, flipping once, until caramelized and tender at the thickest point.',
      'Grind toasted hazelnuts, coriander, cumin, and sesame in spice grinder to a coarse rubble — not powder.',
      'Season dukkah with salt; store excess airtight (keeps 2 weeks).',
      'Whisk tahini with lemon juice, garlic, sumac, and ice water until pourable and smooth.',
      'Smear tahini sauce across the base of a serving plate.',
      'Arrange roasted carrots over tahini; shower generously with dukkah.',
      'Garnish with micro herbs and a final pinch of sumac; serve warm.',
    ],
    badge: 'Plate-up',
  },
  {
    id: 'r33',
    title: 'Miso-Glazed Eggplant Donburi',
    cuisine: 'japanese', cuisineName: 'Japanese',
    photo: 'bowl', photoLabel: 'eggplant · miso · rice',
    why: 'Saikyo miso glaze caramelizes under broiler; eggplant turns custardy. Naturally plant-based, weeknight-easy.',
    prep: '30m', serves: 4, difficulty: 1, cost: 2.85,
    ingredients: [
      'Japanese eggplant — 4 medium, halved lengthwise and scored',
      'White shiro miso (Saikyo-style) — 3 tbsp',
      'Mirin — 2 tbsp',
      'Sake — 1 tbsp',
      'Sugar — 1 tsp',
      'Short-grain Japanese rice — 2 cups, cooked',
      'Scallion — 3, thinly sliced',
      'Toasted sesame seeds — 1 tsp',
      'Toasted sesame oil — 1 tsp, for garnish',
      'Shichimi togarashi — pinch, for heat',
      'Neutral oil — 2 tbsp, for searing',
      'Pickled daikon (takuan) — 4 tbsp, for service',
    ],
    equipment: ['Broiler', 'Rice cooker'],
    subs: [
      ['White miso', 'Chickpea miso (soy-free)'],
      ['Sake', 'Dry white wine + pinch of salt (if sake unavailable)'],
      ['Japanese eggplant', 'Globe eggplant halved (larger, same method)'],
    ],
    steps: [
      'Whisk miso, mirin, sake, and sugar until smooth to form the dengaku glaze.',
      'Score eggplant flesh in deep crosshatch; brush cut surfaces with neutral oil.',
      'Sear eggplant cut-side down in a hot skillet 3 min until golden.',
      'Flip; spread miso glaze generously over scored surface.',
      'Broil at high heat 5–7 min until glaze blisters and caramelizes; flesh should be completely soft.',
      'Portion hot rice into bowls; lay glazed eggplant halves on top.',
      'Drizzle with sesame oil; scatter scallion, sesame seeds, and shichimi.',
      'Serve with pickled daikon on the side; eat immediately while glaze is still caramelized.',
    ],
    badge: 'Weeknight hero',
  },
];

// Allergen tagging — derive `allergens` per recipe by scanning the title,
// source, why-text, ingredients, and substitutions. Drives the diet filter
// on the Menus page (gluten-free / nut-free / soy-free / coconut-free).
//
// Per-recipe overrides go in ALLERGEN_OVERRIDES below — useful when the
// derive picks up a false positive (e.g. a sub-line that says "gluten-free")
// or misses a hidden ingredient (e.g. a stock that contains soy).
const ALLERGEN_PATTERNS = {
  gluten:  /seitan|wheat protein|wheat gluten|bulgur|breadcrumb|orzo|baguette|pita|brioche|ramen|ramyeon|udon|chow mein|lo mein|wheat noodle|tortilla|phyllo|strudel|samosa|churros?\b|loukoumades|sambusa|sourdough|bucatini|pasta|pretzel|gingersnap|barley|rye|spelt|farro|couscous|seitan sausage/i,
  nuts:    /\b(cashew|almond|peanut|walnut|hazelnut|pine nut|pistachio|pecan|brazil nut|macadamia)s?\b/i,
  soy:     /\b(soy|tofu|tempeh|miso|hoisin|tamari|edamame|soybean|gochujang|fermented bean curd|soy sauce|soy milk|soy curls?)\b/i,
  coconut: /\bcoconut\b/i,
};

// Per-recipe overrides keyed by id. Use { add: [...], remove: [...] }
// to nudge the derived list when the regex misses a hidden allergen
// or flags one that isn't in the base recipe.
const ALLERGEN_OVERRIDES = {
  // r09 and r10 use corn tortillas (naturally gluten-free); the regex hits 'tortilla'
  // generically. Remove the false-positive gluten tag via override.
  'r09': { remove: ['gluten'] },
  'r10': { remove: ['gluten'] },
};

// Note: r.subs is intentionally excluded from the text scan. Substitutions
// are *alternatives* a chef can swap in (often to AVOID an allergen) — so
// scanning them flags the base recipe as containing allergens it doesn't
// actually have (e.g. "Soy milk → Cashew cream" would falsely add nuts).
function deriveAllergens(r) {
  const text = [
    r.title, r.source, r.why,
    ...(r.ingredients || []),
  ].join(' ​ ');
  const found = Object.entries(ALLERGEN_PATTERNS)
    .filter(([, re]) => re.test(text))
    .map(([k]) => k);
  const ov = ALLERGEN_OVERRIDES[r.id] || {};
  const set = new Set(found);
  (ov.add || []).forEach(a => set.add(a));
  (ov.remove || []).forEach(a => set.delete(a));
  return [...set];
}

RECIPES.forEach(r => { r.allergens = deriveAllergens(r); });

window.CUISINES = CUISINES;
window.RECIPES = RECIPES;
window.PALETTES = PALETTES;
window.PhotoPH = PhotoPH;
window.paletteFor = paletteFor;
