// Recipe data — meat-dish-forward titles with cruelty-free phrasing in each language.
// Title format: "[Familiar dish name] ([cruelty-free phrase])"

const CUISINES = [
  { id: "all",            name: "All",             tag: "Cruelty-free, restaurant-grade" },
  { id: "italian",        name: "Italian",         tag: "Senza crudeltà" },
  { id: "french",         name: "French",          tag: "Sans cruauté" },
  { id: "german",         name: "German",          tag: "Tierleidfrei" },
  { id: "indian",         name: "Indian",          tag: "क्रूरता मुक्त · Kroorta mukt" },
  { id: "mexican",        name: "Mexican",         tag: "Sin crueldad" },
  { id: "japanese",       name: "Japanese",        tag: "虐待なし · Gyakutai nashi" },
  { id: "thai",           name: "Thai",            tag: "ปราศจากการทารุณกรรม · Pratsachak kan tharunakam" },
  { id: "chinese",        name: "Chinese",         tag: "无虐待 · Wú nüèdài" },
  { id: "middle-eastern", name: "Middle Eastern",  tag: "بدون قسوة · Bidun qaswa" },
  { id: "mediterranean",  name: "Mediterranean",   tag: "Χωρίς σκληρότητα · Chorís sklirótita" },
  { id: "american",       name: "American",        tag: "No Cruelty"},
  { id: "korean",         name: "Korean",          tag: "동물 학대 없음 · Dongmul hakdae eops-eum" },
  { id: "vietnamese",     name: "Vietnamese",      tag: "Không ngược đãi" },
  { id: "caribbean",      name: "Caribbean",       tag: "No Cruelty"},
  { id: "ethiopian",      name: "Ethiopian",       tag: "ያለ ግፍ · Yale gif" },
  { id: "spanish",        name: "Spanish",         tag: "Sin crueldad" },
];

function PhotoPH({ palette, label, dish }) {
  const bg = palette[0];
  const a = palette[1];
  const b = palette[2];
  let layers = "";
  if (dish === "bowl") {
    layers = `
      radial-gradient(ellipse 55% 38% at 50% 60%, ${a} 0%, ${a} 35%, transparent 60%),
      radial-gradient(ellipse 30% 18% at 50% 56%, ${b} 0%, transparent 70%),
      radial-gradient(circle at 30% 35%, oklch(0.96 0.02 85 / 0.18) 0%, transparent 30%)
    `;
  } else if (dish === "plate") {
    layers = `
      radial-gradient(circle at 50% 55%, ${a} 0%, ${a} 32%, transparent 34%),
      radial-gradient(circle at 50% 55%, ${b} 0%, ${b} 18%, transparent 20%),
      radial-gradient(circle at 35% 45%, oklch(0.96 0.02 85 / 0.2) 0%, transparent 18%)
    `;
  } else if (dish === "flat") {
    layers = `
      linear-gradient(135deg, ${a} 0%, ${a} 50%, ${b} 50%, ${b} 100%),
      radial-gradient(circle at 30% 30%, oklch(0.96 0.02 85 / 0.2) 0%, transparent 25%)
    `;
  } else {
    layers = `
      linear-gradient(180deg, transparent 0%, transparent 55%, ${a} 55%, ${a} 75%, ${b} 75%, ${b} 100%),
      radial-gradient(ellipse 40% 20% at 50% 55%, ${a} 0%, transparent 70%)
    `;
  }
  return (
    <div className="photo-ph" style={{
      background: `${layers}, ${bg}`,
    }}>
      <div className="label">{label || "food photo"}</div>
    </div>
  );
}

const PALETTES = {
  italian: ['oklch(0.72 0.12 35)', 'oklch(0.55 0.16 28)', 'oklch(0.85 0.08 90)'],
  french: ['oklch(0.78 0.06 80)', 'oklch(0.65 0.10 70)', 'oklch(0.42 0.08 50)'],
  german: ['oklch(0.50 0.10 50)', 'oklch(0.65 0.10 70)', 'oklch(0.42 0.08 40)'],
  indian: ['oklch(0.62 0.16 60)', 'oklch(0.55 0.18 35)', 'oklch(0.75 0.14 85)'],
  mexican: ['oklch(0.58 0.16 30)', 'oklch(0.70 0.16 70)', 'oklch(0.55 0.15 140)'],
  japanese: ['oklch(0.78 0.04 130)', 'oklch(0.45 0.10 30)', 'oklch(0.92 0.02 100)'],
  thai: ['oklch(0.70 0.15 75)', 'oklch(0.55 0.16 140)', 'oklch(0.62 0.18 30)'],
  chinese: ['oklch(0.55 0.16 30)', 'oklch(0.42 0.10 50)', 'oklch(0.78 0.12 75)'],
  'middle-eastern': ['oklch(0.62 0.10 60)', 'oklch(0.50 0.12 40)', 'oklch(0.75 0.10 90)'],
  mediterranean: ['oklch(0.68 0.14 140)', 'oklch(0.78 0.10 90)', 'oklch(0.55 0.14 35)'],
  american: ['oklch(0.55 0.14 35)', 'oklch(0.72 0.13 75)', 'oklch(0.42 0.08 50)'],
  korean: ['oklch(0.55 0.18 30)', 'oklch(0.62 0.16 140)', 'oklch(0.85 0.06 90)'],
  vietnamese: ['oklch(0.72 0.14 130)', 'oklch(0.78 0.10 80)', 'oklch(0.55 0.14 35)'],
  caribbean: ['oklch(0.68 0.16 70)', 'oklch(0.55 0.16 140)', 'oklch(0.58 0.16 30)'],
  ethiopian: ['oklch(0.55 0.14 50)', 'oklch(0.45 0.10 30)', 'oklch(0.78 0.10 90)'],
  spanish: ['oklch(0.62 0.16 50)', 'oklch(0.78 0.13 75)', 'oklch(0.45 0.12 30)'],
};

function paletteFor(c) { return PALETTES[c] || PALETTES.italian; }

const RECIPES = [
  {
    id: 'r01',
    title: 'Bistecca alla Fiorentina (Senza crudeltà)',
    source: 'Watermelon · seared & smoked',
    cuisine: 'italian', cuisineName: 'Italian',
    photo: 'plate', photoLabel: 'steak · char · rosemary',
    why: 'Compressed watermelon takes a hard cast-iron sear; reads as rare T-bone, plates whole at the table.',
    prep: '40m', serves: 2, difficulty: 3, cost: 4.20,
    ingredients: ['Watermelon', 'Cast-iron salt', 'Rosemary', 'Black pepper', 'Olive oil'],
    equipment: ['Cast iron', 'Vacuum sealer', 'Smoker'],
    subs: [['Watermelon', 'King trumpet (year-round)']],
    badge: 'Showpiece',
  },
  {
    id: 'r02',
    title: 'Ossobuco (Senza crudeltà)',
    source: 'Celeriac · slow-braised',
    cuisine: 'italian', cuisineName: 'Italian',
    photo: 'bowl', photoLabel: 'braise · gremolata · marrow',
    why: 'Whole celeriac braises 3 hours in red wine; "marrow" is cashew-miso butter spooned at the pass.',
    prep: '3h', serves: 4, difficulty: 2, cost: 4.80,
    ingredients: ['Celeriac', 'Red wine', 'Tomato', 'Cashew-miso butter', 'Gremolata'],
    equipment: ['Dutch oven', 'Blender'],
    subs: [['Celeriac', 'King trumpet']],
    badge: 'Sunday service',
  },
  {
    id: 'r03',
    title: 'Steak Frites (Sans cruauté)',
    source: 'King trumpet · seared',
    cuisine: 'french', cuisineName: 'French',
    photo: 'flat', photoLabel: 'steak · frites · béarnaise',
    why: 'Score and press king trumpets into hanger-steak shape; double-fry frites; aquafaba béarnaise holds 2h.',
    prep: '35m', serves: 2, difficulty: 2, cost: 5.10,
    ingredients: ['King trumpet', 'Idaho potato', 'Aquafaba', 'Tarragon', 'Shallot'],
    equipment: ['Cast iron', 'Fryer', 'Blender'],
    subs: [['King trumpet', 'Lion\'s mane']],
    badge: 'Bistro classic',
  },
  {
    id: 'r04',
    title: 'Bœuf Bourguignon (Sans cruauté)',
    source: 'Cremini & seitan · braised',
    cuisine: 'french', cuisineName: 'French',
    photo: 'bowl', photoLabel: 'stew · red wine · pearl onion',
    why: 'Deep red-wine braise with seared seitan; tastes like 4-hour beef stew, ready in 50 minutes.',
    prep: '50m', serves: 6, difficulty: 2, cost: 4.20,
    ingredients: ['Seitan', 'Cremini', 'Burgundy', 'Pearl onion', 'Tomato paste'],
    equipment: ['Dutch oven'],
    subs: [['Seitan', 'King trumpet (gluten-free)']],
    badge: 'Crowd favorite',
  },
  {
    id: 'r05',
    title: 'Sauerbraten (Tierleidfrei)',
    source: 'Seitan · 3-day marinated',
    cuisine: 'german', cuisineName: 'German',
    photo: 'plate', photoLabel: 'braise · gingersnap · red cabbage',
    why: 'Three-day red-wine-vinegar marinade penetrates seitan like a real Sauerbraten roast; gingersnap gravy thickens at service.',
    prep: '3d marinade · 60m cook', serves: 6, difficulty: 3, cost: 4.10,
    ingredients: ['Seitan', 'Red wine vinegar', 'Cloves', 'Gingersnap', 'Juniper'],
    equipment: ['Dutch oven', 'Vacuum bag'],
    subs: [['Seitan', 'King trumpet (gluten-free)']],
    badge: 'Sunday service',
  },
  {
    id: 'r06',
    title: 'Currywurst (Tierleidfrei)',
    source: 'House-made seitan sausage',
    cuisine: 'german', cuisineName: 'German',
    photo: 'flat', photoLabel: 'sausage · curry · ketchup',
    why: 'Seitan sausage poaches in batches; curry-ketchup is your one sauce. Imbiss-ready in 90 seconds.',
    prep: '40m', serves: 6, difficulty: 1, cost: 2.40,
    ingredients: ['Vital wheat gluten', 'Marjoram', 'Curry powder', 'Tomato', 'Smoked paprika'],
    equipment: ['Steamer', 'Cast iron'],
    subs: [['Wheat gluten', 'Tofu base (gluten-free)']],
    badge: 'Quick-fire',
  },
  {
    id: 'r07',
    title: 'Butter Chicken (Kroorta mukt)',
    source: 'Cauliflower · charred',
    cuisine: 'indian', cuisineName: 'Indian',
    photo: 'bowl', photoLabel: 'tomato · cream · charred florets',
    why: 'Tandoor-charred cauliflower in a cashew-tomato gravy; the table can\'t tell. Sauce holds 3 days.',
    prep: '40m', serves: 6, difficulty: 2, cost: 3.10,
    ingredients: ['Cauliflower', 'Cashews', 'Tomato', 'Fenugreek', 'Garam masala'],
    equipment: ['Tandoor or grill', 'Blender', 'Heavy pot'],
    subs: [['Cauliflower', 'Soy curls'], ['Cashews', 'Almonds']],
    badge: 'Crowd favorite',
  },
  {
    id: 'r08',
    title: 'Lamb Rogan Josh (Kroorta mukt)',
    source: 'Jackfruit & black lentil',
    cuisine: 'indian', cuisineName: 'Indian',
    photo: 'bowl', photoLabel: 'kashmiri · chile · yogurt',
    why: 'Slow-cooked jackfruit pulls like lamb shoulder; black lentils provide the fat and structure.',
    prep: '90m', serves: 8, difficulty: 2, cost: 2.40,
    ingredients: ['Young jackfruit', 'Whole urad', 'Kashmiri chile', 'Cardamom', 'Coconut yogurt'],
    equipment: ['Pressure cooker', 'Heavy pot'],
    subs: [['Jackfruit', 'Soy curls']],
    badge: 'Service-friendly',
  },
  {
    id: 'r09',
    title: 'Carnitas Tacos (Sin crueldad)',
    source: 'Jackfruit & oyster mushroom',
    cuisine: 'mexican', cuisineName: 'Mexican',
    photo: 'flat', photoLabel: 'pulled · char · lime',
    why: 'Jackfruit-mushroom blend confit\'d in olive oil; crisped on the flat-top to order. Two-minute build.',
    prep: '60m', serves: 8, difficulty: 2, cost: 2.80,
    ingredients: ['Young jackfruit', 'Oyster mushroom', 'Orange', 'Bay leaf', 'Tortilla'],
    equipment: ['Heavy pot', 'Flat-top'],
    subs: [['Oyster mushroom', 'King oyster']],
    badge: 'Quick-fire',
  },
  {
    id: 'r10',
    title: 'Beef Birria (Sin crueldad)',
    source: 'Soy curls & beet',
    cuisine: 'mexican', cuisineName: 'Mexican',
    photo: 'bowl', photoLabel: 'birria · guajillo · consomé',
    why: 'Five-chile broth with beet-blooded soy curls; consomé is the showstopper, holds in a bain-marie.',
    prep: '75m', serves: 6, difficulty: 3, cost: 3.40,
    ingredients: ['Soy curls', 'Guajillo', 'Ancho', 'Beet', 'Mexican oregano'],
    equipment: ['Stock pot', 'High-speed blender'],
    subs: [['Soy curls', 'Jackfruit (soy-free)']],
    badge: 'Showpiece',
  },
  {
    id: 'r11',
    title: 'Wagyu Donburi (Gyakutai nashi)',
    source: 'King trumpet · seared',
    cuisine: 'japanese', cuisineName: 'Japanese',
    photo: 'bowl', photoLabel: 'rice · sear · scallion',
    why: 'King trumpets sliced thin, seared rare in a soy-mirin glaze; reads as wagyu over koshihikari.',
    prep: '20m', serves: 4, difficulty: 1, cost: 3.60,
    ingredients: ['King trumpet', 'Koshihikari rice', 'Soy', 'Mirin', 'Scallion'],
    equipment: ['Carbon-steel pan', 'Rice cooker'],
    subs: [['King trumpet', 'Hen-of-the-woods']],
    badge: 'Weeknight hero',
  },
  {
    id: 'r12',
    title: 'Tonkotsu Ramen (Gyakutai nashi)',
    source: 'Soy milk & shiitake dashi',
    cuisine: 'japanese', cuisineName: 'Japanese',
    photo: 'bowl', photoLabel: 'ramen · cloud · tare',
    why: 'Soy-milk emulsion mimics tonkotsu\'s collagen body; shiitake-kombu dashi does the porcine work.',
    prep: '60m', serves: 6, difficulty: 2, cost: 3.95,
    ingredients: ['Soy milk', 'Dried shiitake', 'Kombu', 'Ramen noodles', 'Marinated tofu'],
    equipment: ['Stock pot', 'Mesh strainer'],
    subs: [['Soy milk', 'Cashew cream (soy-free)']],
    badge: 'Broth-forward',
  },
  {
    id: 'r13',
    title: 'Massaman Beef Curry (ปราศจากการทารุณกรรม)',
    source: 'Soy curls & potato',
    cuisine: 'thai', cuisineName: 'Thai',
    photo: 'bowl', photoLabel: 'curry · peanut · cardamom',
    why: 'Toasted spice paste freezes in batches; soy curls absorb 30 minutes of simmering coconut.',
    prep: '40m', serves: 4, difficulty: 2, cost: 3.40,
    ingredients: ['Soy curls', 'Potato', 'Coconut milk', 'Massaman paste', 'Peanut'],
    equipment: ['Heavy pot', 'Mortar'],
    subs: [['Soy curls', 'Jackfruit'], ['Peanut', 'Cashew']],
    badge: 'Aromatic',
  },
  {
    id: 'r13b',
    title: 'Som Tam · Green Papaya Salad',
    cuisine: 'thai', cuisineName: 'Thai',
    photo: 'flat', photoLabel: 'papaya · lime · chile',
    why: 'Pounded to order in the mortar; bright, crunchy, naturally plant-based. 4-minute counter dish.',
    prep: '10m', serves: 2, difficulty: 1, cost: 1.80,
    ingredients: ['Green papaya', 'Lime', 'Bird\'s eye chile', 'Long bean', 'Peanut'],
    equipment: ['Mortar & pestle'],
    subs: [['Peanut', 'Cashew'], ['Fish sauce', 'Soy + lime']],
    badge: 'Cold prep',
  },
  {
    id: 'r14',
    title: 'Pad Krapow Moo (ปราศจากการทารุณกรรม)',
    source: 'Crumbled tofu & mushroom',
    cuisine: 'thai', cuisineName: 'Thai',
    photo: 'flat', photoLabel: 'wok · basil · chile',
    why: 'High-heat wok sear with holy basil; six minutes start to finish, plates over jasmine rice.',
    prep: '15m', serves: 2, difficulty: 1, cost: 2.40,
    ingredients: ['Firm tofu', 'King oyster', 'Holy basil', 'Bird\'s eye chile', 'Soy'],
    equipment: ['Carbon-steel wok', 'High BTU burner'],
    subs: [['Tofu', 'Soy curls']],
    badge: 'Wok-fired',
  },
  {
    id: 'r15',
    title: 'Char Siu (Wú nüèdài)',
    source: 'Seitan · lacquered',
    cuisine: 'chinese', cuisineName: 'Chinese',
    photo: 'plate', photoLabel: 'lacquer · five-spice · char',
    why: 'Five-spice seitan glazed with hoisin-maltose; the lacquer crackles like real char siu under the broiler.',
    prep: '50m', serves: 6, difficulty: 2, cost: 3.10,
    ingredients: ['Seitan', 'Hoisin', 'Maltose syrup', 'Five-spice', 'Fermented bean curd'],
    equipment: ['Broiler', 'Hooks or rack'],
    subs: [['Seitan', 'King trumpet (gluten-free)']],
    badge: 'Showpiece',
  },
  {
    id: 'r16',
    title: 'Kung Pao Chicken (Wú nüèdài)',
    source: 'Soy curls & peanut',
    cuisine: 'chinese', cuisineName: 'Chinese',
    photo: 'flat', photoLabel: 'wok · sichuan · peanut',
    why: 'Mala heat from Sichuan peppercorn, blistered chiles, soy curls. Eight minutes wok-fired.',
    prep: '20m', serves: 4, difficulty: 2, cost: 2.70,
    ingredients: ['Soy curls', 'Sichuan peppercorn', 'Peanut', 'Black vinegar', 'Scallion'],
    equipment: ['Wok'],
    subs: [['Soy curls', 'Tempeh']],
    badge: 'Mala',
  },
  {
    id: 'r17',
    title: 'Lamb Shawarma (Bidun qaswa)',
    source: 'Seitan · spit-style',
    cuisine: 'middle-eastern', cuisineName: 'Middle Eastern',
    photo: 'flat', photoLabel: 'spit · spice · pita',
    why: 'Layered seitan stack roasts upright like a real spit; carved to order, plates with toum and pickle.',
    prep: '70m', serves: 8, difficulty: 3, cost: 3.80,
    ingredients: ['Seitan', 'Baharat', 'Pita', 'Toum', 'Sumac onion'],
    equipment: ['Vertical roaster or oven', 'Mandoline'],
    subs: [['Seitan', 'King oyster (gluten-free)']],
    badge: 'Plate-forward',
  },
  {
    id: 'r18',
    title: 'Lamb Kibbeh (Bidun qaswa)',
    source: 'Lentil & walnut',
    cuisine: 'middle-eastern', cuisineName: 'Middle Eastern',
    photo: 'plate', photoLabel: 'kibbeh · pomegranate · mint',
    why: 'Lentil-walnut filling holds the shape of classic kibbeh; fries to a clean shell, plates with tahini.',
    prep: '50m', serves: 8, difficulty: 2, cost: 1.90,
    ingredients: ['Brown lentils', 'Walnut', 'Bulgur', 'Allspice', 'Onion'],
    equipment: ['Food processor', 'Fryer'],
    subs: [['Walnut', 'Pumpkin seed (nut-free)']],
    badge: 'High-margin',
  },
  {
    id: 'r19',
    title: 'Paella de Marisc (Chorís sklirótita)',
    source: 'Hearts of palm & oyster mushroom',
    cuisine: 'mediterranean', cuisineName: 'Mediterranean',
    photo: 'flat', photoLabel: 'saffron · socarrat · paella',
    why: 'Hearts of palm read as squid rings; oyster mushrooms as scallops. Socarrat is real either way.',
    prep: '45m', serves: 6, difficulty: 2, cost: 4.10,
    ingredients: ['Bomba rice', 'Hearts of palm', 'Oyster mushroom', 'Saffron', 'Smoked paprika'],
    equipment: ['Paella pan', 'High-BTU burner'],
    subs: [['Hearts of palm', 'King trumpet rounds']],
    badge: 'Tableside',
  },
  {
    id: 'r19b',
    title: 'Mujadara · Lentil & Caramelized Onion',
    cuisine: 'middle-eastern', cuisineName: 'Middle Eastern',
    photo: 'layered', photoLabel: 'lentil · rice · onion',
    why: 'One-pot lentil-rice; deeply caramelized onion is the only garnish. Naturally plant-based, high-margin.',
    prep: '50m', serves: 8, difficulty: 1, cost: 1.45,
    ingredients: ['Brown lentils', 'Basmati', 'Yellow onion', 'Cumin', 'Olive oil'],
    equipment: ['Heavy pot', 'Wide skillet'],
    subs: [['Basmati', 'Long-grain']],
    badge: 'High-margin',
  },
  {
    id: 'r20',
    title: 'Souvlaki (Chorís sklirótita)',
    source: 'Marinated seitan',
    cuisine: 'mediterranean', cuisineName: 'Mediterranean',
    photo: 'flat', photoLabel: 'skewer · oregano · lemon',
    why: 'Hard char on the grill; tzatziki holds 3 days. Plate with pita, tomato, oregano. 12-min line build.',
    prep: '25m', serves: 4, difficulty: 1, cost: 3.20,
    ingredients: ['Seitan', 'Oregano', 'Lemon', 'Cashew tzatziki', 'Pita'],
    equipment: ['Grill', 'Skewers'],
    subs: [['Seitan', 'King trumpet']],
    badge: 'Quick-fire',
  },
  {
    id: 'r21',
    title: 'Smoked Brisket (No Cruelty)',
    source: 'Tempeh · 4h smoked',
    cuisine: 'american', cuisineName: 'American',
    photo: 'layered', photoLabel: 'bark · smoke ring · slice',
    why: 'Tempeh slabs build a real bark in 4 hours of low smoke; develops pink ring with curing salt.',
    prep: '4h', serves: 8, difficulty: 3, cost: 4.40,
    ingredients: ['Tempeh', 'Smoked paprika', 'Curing salt', 'Coffee', 'Brown sugar'],
    equipment: ['Smoker', 'Probe thermometer'],
    subs: [['Tempeh', 'King oyster (soy-free)']],
    badge: 'Customer favorite',
  },
  {
    id: 'r22',
    title: 'Ribeye Plate (No Cruelty)',
    source: 'Wheat-protein steak · marbled',
    cuisine: 'american', cuisineName: 'American',
    photo: 'plate', photoLabel: 'sear · grain · jus',
    why: 'Laminated wheat protein with beet-marbling; sears with a real crust. Plate with roasted bone-marrow oil.',
    prep: '30m', serves: 2, difficulty: 3, cost: 5.40,
    ingredients: ['Vital wheat gluten', 'Beet', 'Mushroom stock', 'Black pepper', 'Bone-marrow oil'],
    equipment: ['Cast iron', 'Steamer'],
    subs: [['Wheat protein', 'Layered king oyster (gluten-free)']],
    badge: 'Fine-dining',
  },
  {
    id: 'r23',
    title: 'Korean Hotpot · Budae Jjigae (동물 학대 없음)',
    source: 'Seitan sausage & tofu',
    cuisine: 'korean', cuisineName: 'Korean',
    photo: 'bowl', photoLabel: 'hotpot · gochujang · ramyeon',
    why: 'Army-stew base with seitan sausage and tofu; tabletop simmer is the show. Broth holds in service well.',
    prep: '35m', serves: 4, difficulty: 1, cost: 3.60,
    ingredients: ['Seitan sausage', 'Firm tofu', 'Gochujang', 'Kimchi', 'Ramyeon'],
    equipment: ['Tabletop burner', 'Earthenware pot'],
    subs: [['Seitan sausage', 'Mushroom medley (gluten-free)']],
    badge: 'Tableside',
  },
  {
    id: 'r24',
    title: 'Galbi Short Rib (동물 학대 없음)',
    source: 'King trumpet · scored',
    cuisine: 'korean', cuisineName: 'Korean',
    photo: 'flat', photoLabel: 'galbi · pear · sesame',
    why: 'Asian-pear marinade tenderizes scored king trumpet; sears in 90 seconds, eats like short rib.',
    prep: '30m', serves: 4, difficulty: 2, cost: 3.80,
    ingredients: ['King trumpet', 'Asian pear', 'Soy', 'Sesame', 'Garlic'],
    equipment: ['Tabletop grill or cast iron'],
    subs: [['King trumpet', 'Tempeh']],
    badge: 'Interactive',
  },
  {
    id: 'r25',
    title: 'Phở Bò (Không ngược đãi)',
    source: 'Charred onion broth & soy curls',
    cuisine: 'vietnamese', cuisineName: 'Vietnamese',
    photo: 'bowl', photoLabel: 'pho · star anise · basil',
    why: 'Charred onion-ginger broth with a 6-spice tea infusion gets the savory depth. Soy curls slice in.',
    prep: '60m', serves: 6, difficulty: 2, cost: 3.10,
    ingredients: ['Soy curls', 'Star anise', 'Cinnamon', 'Charred onion', 'Rice noodle'],
    equipment: ['Stock pot', 'Mesh strainer'],
    subs: [['Soy curls', 'Tofu (soy-only)']],
    badge: 'Lunch hero',
  },
  {
    id: 'r26',
    title: 'Jamaican Jerk Chicken (No Cruelty)',
    source: 'King oyster & jackfruit',
    cuisine: 'caribbean', cuisineName: 'Caribbean',
    photo: 'flat', photoLabel: 'jerk · pimento · lime',
    why: 'Pimento-wood smoke on king oyster "drumsticks"; jerk paste keeps two weeks for service.',
    prep: '40m', serves: 6, difficulty: 2, cost: 3.50,
    ingredients: ['King oyster', 'Young jackfruit', 'Scotch bonnet', 'Allspice', 'Thyme'],
    equipment: ['Grill', 'Heavy pot'],
    subs: [['King oyster', 'Tempeh']],
    badge: 'Bold',
  },
  {
    id: 'r27',
    title: 'Doro Wat (Yale gif)',
    source: 'Soy curls & berbere',
    cuisine: 'ethiopian', cuisineName: 'Ethiopian',
    photo: 'plate', photoLabel: 'berbere · injera · onion',
    why: 'Slow-cooked with deeply caramelized onion and berbere; injera tears at the table.',
    prep: '70m', serves: 6, difficulty: 2, cost: 2.40,
    ingredients: ['Soy curls', 'Berbere', 'Onion', 'Injera', 'Niter kibbeh (vegan)'],
    equipment: ['Heavy pot', 'Crepe pan'],
    subs: [['Soy curls', 'Cremini mushroom']],
    badge: 'Experiential',
  },
  {
    id: 'r27b',
    title: 'Misir Wat · Berbere Lentil Stew',
    cuisine: 'ethiopian', cuisineName: 'Ethiopian',
    photo: 'plate', photoLabel: 'lentil · berbere · injera',
    why: 'Slow-cooked red lentils with berbere; injera tears at the table. Naturally plant-based.',
    prep: '60m', serves: 6, difficulty: 2, cost: 2.20,
    ingredients: ['Red lentils', 'Berbere', 'Onion', 'Injera', 'Niter kibbeh (vegan)'],
    equipment: ['Heavy pot', 'Crepe pan'],
    subs: [['Niter kibbeh', 'Olive oil + spices']],
    badge: 'Experiential',
  },
  {
    id: 'r28',
    title: 'Chorizo a la Sidra (Sin crueldad)',
    source: 'Smoked seitan',
    cuisine: 'spanish', cuisineName: 'Spanish',
    photo: 'plate', photoLabel: 'chorizo · cider · smoke',
    why: 'Smoked seitan chorizo flamed in hard cider tableside; tapas-bar theater, two-minute service.',
    prep: '30m', serves: 4, difficulty: 1, cost: 3.10,
    ingredients: ['Seitan', 'Smoked paprika', 'Hard cider', 'Garlic', 'Bay'],
    equipment: ['Cast iron', 'Long matches'],
    subs: [['Seitan', 'King trumpet (gluten-free)']],
    badge: 'Tableside',
  },
  {
    id: 'r29',
    title: 'Albóndigas (Sin crueldad)',
    source: 'Lentil & mushroom',
    cuisine: 'spanish', cuisineName: 'Spanish',
    photo: 'bowl', photoLabel: 'meatball · tomato · sherry',
    why: 'Lentil-mushroom meatballs hold their shape in the sherry-tomato sauce; freezer-friendly batch of 100.',
    prep: '45m', serves: 8, difficulty: 1, cost: 1.80,
    ingredients: ['Brown lentil', 'Cremini', 'Sherry', 'Tomato', 'Smoked paprika'],
    equipment: ['Food processor', 'Heavy pot'],
    subs: [['Brown lentil', 'Black bean']],
    badge: 'Batch-cook',
  },
  {
    id: 'r30',
    title: 'Polpette al Sugo (Senza crudeltà)',
    source: 'Eggplant & breadcrumb',
    cuisine: 'italian', cuisineName: 'Italian',
    photo: 'bowl', photoLabel: 'meatball · sugo · basil',
    why: 'Roasted eggplant binds with breadcrumb and miso; tomato sugo holds 4 days. Margin king.',
    prep: '50m', serves: 8, difficulty: 1, cost: 1.50,
    ingredients: ['Eggplant', 'Breadcrumb', 'Miso', 'San Marzano', 'Basil'],
    equipment: ['Sheet pan', 'Heavy pot'],
    subs: [['Breadcrumb', 'Almond meal (gluten-free)']],
    badge: 'Margin king',
  },
  {
    id: 'r31',
    title: 'Cacio e Pepe',
    cuisine: 'italian', cuisineName: 'Italian',
    photo: 'plate', photoLabel: 'pasta · pepper · cream',
    why: 'Cashew cream emulsifies in 90 seconds; three pantry ingredients, restaurant-grade silk. Naturally plant-based.',
    prep: '20m', serves: 4, difficulty: 2, cost: 3.40,
    ingredients: ['Bucatini', 'Cashew cream', 'Black pepper', 'Nutritional yeast', 'Pasta water'],
    equipment: ['Blender', 'Large pot', 'Heavy skillet'],
    subs: [['Cashews', 'Sunflower seeds (nut-free)']],
    badge: 'Crowd-pleaser',
  },
  {
    id: 'r32',
    title: 'Roasted Carrot, Tahini & Dukkah',
    cuisine: 'middle-eastern', cuisineName: 'Middle Eastern',
    photo: 'plate', photoLabel: 'carrot · tahini · sumac',
    why: 'Single sheet pan, three textures, plates like a magazine cover. Dukkah keeps for weeks.',
    prep: '40m', serves: 6, difficulty: 1, cost: 2.30,
    ingredients: ['Heritage carrots', 'Tahini', 'Lemon', 'Hazelnut', 'Sumac'],
    equipment: ['Sheet pan', 'Spice grinder'],
    subs: [['Tahini', 'Sunflower butter (nut-free)']],
    badge: 'Plate-up',
  },
  {
    id: 'r33',
    title: 'Miso-Glazed Eggplant Donburi',
    cuisine: 'japanese', cuisineName: 'Japanese',
    photo: 'bowl', photoLabel: 'eggplant · miso · rice',
    why: 'Saikyo miso glaze caramelizes under broiler; eggplant turns custardy. Naturally plant-based, weeknight-easy.',
    prep: '30m', serves: 4, difficulty: 1, cost: 2.85,
    ingredients: ['Japanese eggplant', 'White miso', 'Mirin', 'Short-grain rice', 'Scallion'],
    equipment: ['Broiler', 'Rice cooker'],
    subs: [['White miso', 'Chickpea miso (soy-free)']],
    badge: 'Weeknight hero',
  },
];

window.CUISINES = CUISINES;
window.RECIPES = RECIPES;
window.PALETTES = PALETTES;
window.PhotoPH = PhotoPH;
window.paletteFor = paletteFor;
